kubevirt/ssp-operator

tests/validator_test.go
=> Add test ids for template validator tests

README.md
Signed-off-by: Omer Yahud <oyahud@redhat.com>
=> Added WIP message in readme

OWNERS
Add approver and reviewers alias into OWNERS file
=> Add reviewers and approvers

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Omer Yahud <oyahud@redhat.com>
```release-note
NONE
```
=> Added github templates

Makefile, hack/build-functests.sh, hack/build-in-container.sh, hack/common.sh, hack/config.sh, hack/in-container.sh, hack/run-functest.sh, tests/TESTS.MD, tests/build/Dockerfile, tests/build/entrypoint.sh
Adding a basic test-suite and Make targets for build and running tests against an existing cluster and ssp operator deployed 
=> Add a TestSuite and other utils

Makefile, README.md
Added new information to the `README.md`.
```release-note
NONE
```
=> Update README.md with instructions how to run tests

controllers/ssp_controller.go, internal/operands/metrics/reconcile.go, internal/operands/metrics/reconcile_test.go, internal/operands/operand.go, internal/operands/template-validator/reconcile.go, internal/operands/template-validator/reconcile_test.go, main.go
This change makes it easier to understand which methods should be implemented by operands.
```release-note
NONE
```
=> Create interface for operands

tests/webhook_test.go
@jean-edouard I accidently approved your PR before adding the test-id, so adding it now
/cc @rnetser 
Signed-off-by: Omer Yahud <oyahud@redhat.com>
```release-note
NONE
```
=> Added missing webhook testid

tests/webhook_test.go
=> Fix expected error message in webhook functional test

Dockerfile, config/manager/manager.yaml, config/rbac/role.yaml, controllers/ssp_controller.go, internal/operands/common-templates/reconcile.go, internal/operands/metrics/reconcile.go, internal/operands/node-labeller/reconcile.go, internal/operands/template-validator/reconcile.go
=> Update Dockerfile and add RBAC rules needed to run operator in cluster

tests/commonTemplates_test.go
Add missing test ids
Fixes #
```release-note
NONE
```
=> Add test ids

.gitignore, .travis.yml, Dockerfile, Makefile, config/manager/kustomization.yaml, config/manager/manager.yaml, config/manifests/bases/ssp-operator.clusterserviceversion.yaml, config/manifests/kustomization.yaml, hack/csv-generator.sh, hack/update-csv.py, tests/test-csv-generator.sh
added csv-generator
```NONE
```
=> added csv-generator

.travis.yml, Makefile
When a commit is tagged TravisCI pushes the image to quay.io
and creates a github release.
```release-note
NONE
```
=> Release container and manifests on tag

config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml
Remove the extra proxy sidecar
Fixes #
```release-note
NONE
```
=> Remove the extra proxy sidecar

hack/deploy-kubevirt-and-cdi.sh, hack/deploy-old-ssp-operator.sh
Added scripts used by openshift CI
```release-note
NONE
```
=> Add scripts to deploy kubevirt, cdi  and the old operator

data/crd/ssp.kubevirt.io_ssps.yaml
Run `make container-build` to update data/crd
```release-note
NONE
```
=> Regenerate data/crd

data/common-templates-bundle/common-templates-v0.13.0-rc.0.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.13.0-rc.0.yaml
Fixup for https://github.com/kubevirt/ssp-operator/pull/64 adding lines that somehow got lost in the template files
```release-note
NONE
```
=> Update common template bundle

tests/commonTemplates_test.go
Signed-off-by: Kevin Wiesmueller <kwiesmul@redhat.com>
Adds a functional test to ensure there is only one template marked as default variation per os.
Derived from https://github.com/kubevirt/common-templates/blob/master/automation/test_defaults.sh
This test will currently fail until the common-template bundle in this repository is updated to have the `template.kubevirt.io/default-os-variant` present. This will be done in a separate PR so this can be rebased.
/hold
```release-note
NONE
```
=> Add test ensuring one default template per OS

tests/upgrade_test.go
Fixes #
```release-note
NONE
```
=> Add missing upgrade testid

internal/operands/common-templates/reconcile.go, internal/operands/common-templates/resource.go, tests/commonTemplates_test.go
Adds a functional test to ensure there is only one template for every (os, workload, flavor, version) combination.
Derived from https://github.com/kubevirt/common-templates/blob/master/automation/test_duplicate_templates.sh
Fixes #
```release-note
NONE
```
=> Add duplicate template test

data/common-templates-bundle/common-templates-v0.13.0.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.13.0.yaml, internal/operands/common-templates/resource.go
Update common-template bundle to v0.13.0
Fixes #
```release-note
NONE
```
=> Update common-template bundle to v0.13.0

tests/e2e-test-csv-generator.sh
Fix csv-generator test image tag
```release-note
None
```
=> Fix csv-generator test image tag

data/common-templates-bundle/common-templates-v0.13.1.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.13.1.yaml, internal/operands/common-templates/resource.go
Added template bundle release v0.13.1
```release-note
Add template bundle release v0.13.1
```
=> Common templates release v0.13.1

controllers/ssp_controller.go, internal/common/resource.go, internal/operands/common-templates/reconcile.go, internal/operands/metrics/reconcile.go, internal/operands/node-labeller/reconcile.go, internal/operands/operand.go, internal/operands/template-validator/reconcile.go
Adding some more log messages to make operator logs more informative
```release-note
None
```
=> Adding important log messages

internal/operands/node-labeller/resources.go, internal/operands/template-validator/reconcile.go, internal/operands/template-validator/reconcile_test.go, internal/operands/template-validator/resources.go
Fix minor issues found by GoLand static code inspection.
```release-note
NONE
```
=> Small code cleanup

go.mod, go.sum, vendor/modules.txt
Drop replace directive for cpu-nfd-plugin and update some dependencies
```release-note
NONE
```
=> Drop replace directive for cpu-nfd-plugin and update some dependencies

go.mod, go.sum, tests/tests_suite_test.go, vendor/kubevirt.io/qe-tools/LICENSE, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go, vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go, vendor/modules.txt
Add some polarion and junit flags required by QE to provide reports
```release-note
None
```
=> Integrate flags required by QE to generate reports

.travis.yml, Makefile, hack/csv-generator.go
This PR switches to using csv-generator to generate the ClusterServiceVersion yaml.
Fixes #
```release-note
NONE
```
=> Generate the CSV using csv-generator

.gitignore, data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Previous PR added related images to CSV, but the new CSV was not committed to the repository.
```release-note
NONE
```
=> Regenerate CSV with related images added

data/common-templates-bundle/common-templates-v0.14.0-rc.2.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.14.0-rc.2.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.14.0-rc.2 
```release-note
Update common-templates bundle to v0.14.0-rc.2
```
=> Update common-templates to v0.14.0-rc.2

data/common-templates-bundle/common-templates-v0.13.2.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.13.2.yaml, internal/operands/common-templates/resource.go
backport common templates v0.13.2
```
NONE
```
=> backport common templates v0.13.2

internal/common/cache.go
Adding the UID to the cache will fix issues that can be caused by quickly deleting and recreating a resource.
The operator would see the same resource in cache and not reconcile it.
```release-note
None
```
=> Add UID to VersionCache

internal/operands/template-validator/defaults.go
Updated template-validator to `v0.10.0`.
```release-note
Template validator updated to version v0.10.0
```
=> Update template-validator to version v0.10.0

tests/misc_test.go
Add missing test-ids in misc_tests.go
```release-note
None
```
=> Add missing test ids in misc_tests.go

tests/metrics_test.go
Add missing test ids to metrics_test.go
```release-note
None
```
=> Add missing test ids to metrics_test.go

tests/commonTemplates_test.go
Add missing test ids to commonTemplates_test.go
```release-note
None
```
=> Add missing test ids to commonTemplates_test.go

tests/webhook_test.go
Add missing test ids to webhook_test.go
```release-note
None
```
=> Add misisng test ids to webhook_test.go

data/common-templates-bundle/common-templates-v0.14.0.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.14.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.14.0 
```release-note
Update common-templates bundle to v0.14.0
```
=> Update common-templates to v0.14.0

tests/commonTemplates_test.go, tests/metrics_test.go, tests/nodeLabeller_test.go, tests/validator_test.go, tests/webhook_test.go
Add missing test ids
```release-note
NONE
```
=> Add missing test ids

OWNERS
Nominate kwiesmueller to approvers
/cc @omeryahud @akrejcir @ksimon1 
```release-note
NONE
```
=> Nominate kwiesmueller to approvers

controllers/ssp_controller.go, internal/operands/common-templates/constants.go, internal/operands/common-templates/resource.go, internal/operands/node-labeller/resources.go, internal/operands/template-validator/reconcile_test.go, internal/operands/template-validator/resources.go, tests/commonTemplates_test.go
Fixed code smells found by SonarCloud.
```release-note
None
```
=> Improve code: Use constants instead of string literals

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Moved description text in the templates to a comment, so it will not be shown in the resulting PR or Issue.
```release-note
None
```
=> Cleanup Pull Request and Issue templates

go.mod, go.sum, vendor/modules.txt
Forced versions of:
- github.com/gogo/protobuf
- github.com/gorilla/websocket
```release-note
None
```
=> Force versions of 2 dependencies

go.mod, go.sum, vendor/modules.txt
Forced versions of:
- github.com/gogo/protobuf
- github.com/gorilla/websocket
```release-note
None
```
=> [v0.2] Force versions of 2 dependencies

internal/operands/common-templates/constants.go, tests/commonTemplates_test.go
This adds a missed test from https://github.com/kubevirt/kubevirt-ssp-operator/blob/master/functests/12-test-os-imaes-namespace_rbac.sh#L224-L230
Fixes #
```release-note
NONE
```
=> Add negative service account test

README.md
Adding a little bit to the readme on how to build and push the Template
Validator.
```
NONE
```
=> Adding info on building the Template Validator

config/manager/manager.template.yaml
Fix indentation for resource request in manager deployment
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=1953485
```release-note
NONE
```
=> Correct resources indentation for manager

internal/operands/common-templates/reconcile.go
refactor reconcileOlderTemplates function to reduce its cognitive cmplexity 
```
NONE
```
=> refactor reconcileOlderTemplates function

data/common-templates-bundle/common-templates-v0.15.0.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.15.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.15.0 
```release-note
Update common-templates bundle to v0.15.0
```
=> Update common-templates to v0.15.0

internal/template-validator/webhooks/uplink.go
Fixes code smell https://sonarcloud.io/project/issues?id=kubevirt_ssp-operator&issues=AXkOT7Pl1nk9lrkwAhmY&open=AXkOT7Pl1nk9lrkwAhmY
```release-note
NONE
```
=> explain DeepCopy in template-validator

tests/TESTS.MD
Removes old docs
Fixes #
```release-note
NONE
```
=> Remove old docs

internal/template-validator/validation/specialized.go
Fixes: https://sonarcloud.io/project/issues?id=kubevirt_ssp-operator&issues=AXkOT7Or1nk9lrkwAhmX&open=AXkOT7Or1nk9lrkwAhmX
```release-note
None
```
=> Code change: Fix issue found by sonarcloud

data/common-templates-bundle/common-templates-v0.15.1.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.15.1.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.15.1 
```release-note
Update common-templates bundle to v0.15.1
```
=> Update common-templates to v0.15.1

data/olm-catalog/ssp-operator.clusterserviceversion.yaml
This generated change to CSV was missed in #202 
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=1953485 
```release-note
NONE
```
=> [release-v0.11] Add the missing Generate csv

data/common-templates-bundle/common-templates-v0.16.0.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.16.0 
```release-note
Update common-templates bundle to v0.16.0
```
=> Update common-templates to v0.16.0

data/common-templates-bundle/common-templates-v0.16.1.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.1.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.16.1 
```release-note
Update common-templates bundle to v0.16.1
```
=> Update common-templates to v0.16.1

config/crd/bases/ssp.kubevirt.io_ssps.yaml, data/crd/ssp.kubevirt.io_ssps.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Some of the files were not up to date.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1995295
```release-note
None
```
=> [release-v0.12] Regenerate files by running 'make container-build'

config/crd/bases/ssp.kubevirt.io_ssps.yaml, data/crd/ssp.kubevirt.io_ssps.yaml
Some of the files were not up to date.
```release-note
None
```
=> Regenerate files by running 'make container-build'

hack/csv-generator.go
Reduce cognitive complexity suggested by Sonarcloud
Fixes #
```release-note
NONE
```
=> Reduce cognitive complexity

data/common-templates-bundle/common-templates-v0.16.2.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.2.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.16.2 
```release-note
Update common-templates bundle to v0.16.2
```
=> Update common-templates to v0.16.2

controllers/ssp_controller.go, internal/common/scheme.go, internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go, internal/operands/metrics/reconcile.go, internal/operands/metrics/reconcile_test.go, internal/operands/node-labeller/reconcile.go, internal/operands/operand.go, internal/operands/template-validator/reconcile.go, main.go
Each operand registers needed resources to the global scheme.
This will simplify future PRs.
```release-note
None
```
=> Code change: Add global scheme variable for the operator

tests/tests_common_test.go, tests/tests_suite_test.go
add eventually command to tests which are testing resource permissions
```
NONE
```
/cc @akrejcir
=> add eventually command to tests which are testing resource permissions

tests/commonTemplates_test.go, tests/metrics_test_utils.go, tests/misc_test.go, tests/tests_common_test.go
Add tests for:
* ssp_operator_reconciling_properly
* total_restored_common_templates
```release-note
None
```
=> Add metrics tests

OWNERS
Updated `OWNERS` file to reflect current contributors, and sorted the lists alphabetically.
```release-note
None
```
=> Update OWNERS file to reflect current contributors

.github/workflows/release.yaml
Reverts kubevirt/ssp-operator#253
=> Revert "change ACTIONS_TOKEN to secrets.GITHUB_TOKEN"

data/crd/ssp.kubevirt.io_ssps.yaml
Update `data/crd/ssp.kubevirt.io_ssps.yaml` by running `make container-build`.
```release-note
None
```
=> Regenerate CRD

data/common-templates-bundle/common-templates-v0.17.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.17.0 
```release-note
Update common-templates bundle to v0.17.0
```
=> Update common-templates to v0.17.0

data/common-templates-bundle/common-templates-v0.15.2.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.15.2.yaml, internal/operands/common-templates/version.go
backport common-templates v0.15.2
```
backport common-templates v0.15.2
```
=> backport common-templates v0.15.2

OWNERS
Update OWNERS file to reflect current contributors
```release-note
None
```
=> [v0.1] Update OWNERS file to reflect current contributors

OWNERS
Update OWNERS file to reflect current contributors
```release-note
None
```
=> [v0.11] Update OWNERS file to reflect current contributors

tests/dataSources_test.go
Added `test_id` for one of the tests.
```release-note
None
```
=> Add missing test_id for one of DataImportCron tests

OWNERS
Update OWNERS file to reflect current contributors
```release-note
None
```
=> [v0.12] Update OWNERS file to reflect current contributors

data/common-templates-bundle/common-templates-v0.18.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.18.0 
```release-note
Update common-templates bundle to v0.18.0
```
=> Update common-templates to v0.18.0

tests/dataSources_test.go
Temporarily disable DataImportCron tests due to https://bugzilla.redhat.com/show_bug.cgi?id=2035008
```release-note
None
```
=> Disable failing tests

data/common-templates-bundle/common-templates-v0.16.4.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.4.yaml, internal/operands/common-templates/version.go
Signed-off-by: Dominik Holler <dholler@redhat.com>
```release-note
- update to common-templates v0.16.4 to include RHEL 9 Beta
```
=> Update common-templates bundle to version v0.16.4

data/common-templates-bundle/common-templates-v0.19.0.yaml, internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go, internal/operands/common-templates/version.go, internal/template-bundle/bundle_test.go, internal/template-bundle/template-bundle-test.yaml
Update common-templates bundle to v0.19.0 
```release-note
Update common-templates bundle to v0.19.0
```
=> Update common-templates to v.0.19.0

data/common-templates-bundle/common-templates-v0.19.1.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.19.1 
```release-note
Update common-templates bundle to v0.19.1
```
=> Update common-templates to v0.19.1

internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go
the application of deprecated label was not working correctly,
because it doesn't skip old templates with the same name as newly
deployed templates.
Added a condition, which check if template has newer version than is
the version in ssp operator. If yes, template is not set as deprecated
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2042799
```
NONE
```
=> fix applying deprecated label

data/common-templates-bundle/common-templates-v0.19.2.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.19.2 
```release-note
Update common-templates bundle to v0.19.2
```
=> Update common-templates to v0.19.2

controllers/ssp_controller.go, internal/common/resource.go, internal/operands/common-templates/reconcile.go, main.go
Fix https://bugzilla.redhat.com/show_bug.cgi?id=2037421
```release-note
Changed log level
```
=> Change default log level to be less verbose

data/common-templates-bundle/common-templates-v0.19.3.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.19.3 
```release-note
Update common-templates bundle to v0.19.3
```
=> Update common-templates to v0.19.3

internal/common/resource.go, internal/common/resource_test.go, internal/operands/data-sources/reconcile.go, internal/operands/data-sources/reconcile_test.go, tests/dataSources_test.go
User can remove the label 'cdi.kubevirt.io/dataImportCron' from a DataSource to disable auto-updates.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2051693
```release-note
None
```
=> Fix disabling auto-update for a single DataSource

tests/misc_test.go
Wrapped an update in `Eventually()`, so the test is more stable.
```release-note
None
```
=> Improve SSPOperatorReconcilingProperly metric test

Makefile
This PR fixes `make generate` and `make manifests`.
The `paths` parameter for `controller-gen` had incorrect syntax.
```release-note
None
```
=> Fix 'make generate' and 'make manifests'

data/common-templates-bundle/common-templates-v0.20.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.20.0 
```release-note
Update common-templates bundle to v0.20.0
```
=> Update common-templates to v0.20.0

internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go
The common reconcile method does not remove labels and annotations from resources, which is useful to not remove user-defined labels and annotations.
This PR adds a special logic to remove labels and annotations from templates, if they are not user-defined. For example, if the default template for an OS changes, then the label needs to be removed from the old template.
```release-note
None
```
=> Remove selected template labels on reconcile

data/common-templates-bundle/common-templates-v0.19.4.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to version v0.19.4
```
Update common-templates bundle to version v0.19.4
```
=> [backport release-v0.13] Update common-templates bundle to version v0.19.4

data/common-templates-bundle/common-templates-v0.19.4.yaml
replace CT v0.19.4 with correct file
```
NONE
```
=> replace CT v0.19.4 with correct file

data/common-templates-bundle/common-templates-v0.21.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.21.0 
```release-note
Update common-templates bundle to v0.21.0
```
=> Update common-templates to v0.21.0

Dockerfile, validator.Dockerfile
replaced wget with curl in dockerfile
removed gzip package, run microdnf update before installing packages
```
NONE
```
=> replaced wget with curl in dockerfile

data/common-templates-bundle/common-templates-v0.22.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.22.0 
```release-note
Update common-templates bundle to v0.22.0
```
=> Update common-templates to v0.22.0

data/common-templates-bundle/common-templates-v0.23.1.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.23.1 
```release-note
Update common-templates bundle to v0.23.1
```
=> Update common-templates to v0.23.1

tests/dataSources_test.go
This PR added test_id for newly added feature  Support custom DataImportCron creating in custom namespaces
```
NONE
```
Signed-off-by: Geetika Kapoor <gkapoor@redhat.com>
=> Added test id for custom DataImportCron created in custom namespaces

data/common-templates-bundle/common-templates-v0.19.5.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to version v0.19.5
```
Update common-templates bundle to version v0.19.5
```
=> [release-v0.13] Update common-templates bundle to version v0.19.5

data/common-templates-bundle/common-templates-v0.16.5.yaml, internal/operands/common-templates/version.go
backport of common-templates release v0.16.5
```
Added common-templates v0.16.5
```
=> [release-v0.12] backport of common-templates release v0.16.5

data/common-templates-bundle/common-templates-v0.23.2.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.23.2 
```release-note
Update common-templates bundle to v0.23.2
```
=> Update common-templates to v0.23.2

tests/monitoring_test.go
fix retrieving of prometheus token in tests
This fix is not ideal, because it retrieves all secrets from openshift-monitoring namespace and then iterates through them until it founds correct secret. In this case I can't use label selector, because the secret doesn't have any label and I can't use field selector, because field selector doesn't support regex
```
NONE
```
=> fix retrieving of prometheus token in tests

tests/tests_suite_test.go, tests/webhook_test.go
increase timeout for updating ssp cr for test ids 5990 and 5989
```
NONE
```
=> Increase timeouts for tests 5990 and 5989

data/common-templates-bundle/common-templates-v0.23.3.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.23.3 
```release-note
Update common-templates bundle to v0.23.3
```
=> Update common-templates to v0.23.3

data/common-templates-bundle/common-templates-v0.19.6.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.19.6
```
Update common-templates bundle to v0.19.6
```
=> [backport release-v0.13] Update common-templates bundle to v0.19.6

data/common-templates-bundle/common-templates-v0.16.6.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.6.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.16.6
```
Update common-templates bundle to v0.16.6
```
=> [backport release-v0.12] Update common-templates bundle to v0.16.6

tests/metrics_test.go
This PR adds new test cases for SSP alert definitions. We expect to see `summary`, `runbook_url`, `severity`, `kubernetes_operator_part_of` and `kubernetes_operator_component` for each alert. Those fields must not be empty and some must have specific values.
Signed-off-by: assafad <aadmi@redhat.com>
```release-note
None
```
=> Add sanity tests for SSP alerts

tests/misc_test.go
Waits specifically for DataVolume import, and increases timeout.
```release-note
None
```
=> tests: RHEL: wait for DataVolume import and increase timeout

automation/common/deploy-kubevirt-and-cdi.sh, automation/common/versions.sh
When a new release branch is created, the versions should be fixed.
```release-note
None
```
=> CI: Move versions to a separate file

internal/operands/metrics/resources.go
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>
Web browsers are becoming increasingly vocal about
unencrypted links, let's move to
https to prevent unnecessary noise.
`http://kubevirt.io/monitoring/runbooks/` -> `https://kubevirt.io/monitoring/runbooks/`
Only `http`->`https`
```release-note
NONE
```
=> Use https on runbooks URLs

tests/dataSources_test.go
add debug lines to DataImportCron template tests
These debug lines should help to find out whats wrong with e2e
dataImportCron tests.
```
NONE
```
=> add debug lines to DataImportCron template tests

tests/commonTemplates_test.go, tests/dataSources_test.go, tests/env/env.go, tests/labels_test.go, tests/misc_test.go, tests/monitoring_test.go, tests/service_controller_test.go, tests/single_node_test.go, tests/tests_common_test.go, tests/tests_suite_test.go, tests/validator_test.go, tests/webhook_test.go
Added missing test for webhook functionality, and improved test code.
```release-note
None
```
=> Add missing webhook test and improve tests

data/common-templates-bundle/common-templates-v0.24.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.24.0 
```release-note
Update common-templates bundle to v0.24.0
```
=> Update common-templates to v0.24.0

tests/dataSources_test.go, tests/misc_test.go
This is a backport of https://github.com/kubevirt/ssp-operator/pull/418
```release-note
None
```
=> [release-v0.16] Fix tests waiting for DVs to succeed

Makefile, config/crd/bases/ssp.kubevirt.io_ssps.yaml, config/rbac/role.yaml, config/webhook/manifests.yaml
update controller-gen and kustomize
```
NONE
```
=> update controller-gen and kustomize

data/common-templates-bundle/common-templates-v0.24.1.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.24.1 
```release-note
Update common-templates bundle to v0.24.1
```
=> Update common-templates to v0.24.1

data/crd/ssp.kubevirt.io_ssps.yaml, internal/operands/node-labeller/reconcile.go, internal/template-validator/validation/eval.go
Regenerated files using the new version of controller-gen.
```release-note
None
```
=> Regenerate files by running "make container-build"

data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
```release-note
None
```
=> Add the missing RBAC permissions to clusterversions in the CSV

tests/crypto_policy_test.go
Add test ids to crypto_policy_test.go
```release-note
None
```
=> crypto_policy_test.go: Add test_ids

OWNERS
Lets stop spamming him with review requests now he has left the downstream team. Thanks for everything @borod108!
Fixes #
```release-note
NONE
```
=> OWNERS: Remove borod108 from reviewers

data/common-templates-bundle/common-templates-v0.23.5.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to version v0.23.5
```
Update common-templates bundle to version v0.23.5
```
=> [release-v0.15] Update common-templates bundle to version v0.23.5

README.md, docs/development.md
Add missing README and dev docs.
Fixes #
```release-note
NONE
```
=> common-instancetypes: Add missing README and dev docs

hack/kubevirtci.sh
The correct and already ignored by git name is `_kubevirt-ci`.
Fixes #
```release-note
NONE
```
=> kubevirtci: Correct directory name

data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml
common-instancetypes: Update bundle to v0.0.3-rc
https://github.com/kubevirt/common-instancetypes/releases/tag/v0.0.3-rc
```release-note          
Update common-instancetypes bundle to v0.0.3-rc
```
=> Update common-instancetypes to v0.0.3-rc

data/common-templates-bundle/common-templates-v0.25.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.25.0 
```release-note
Update common-templates bundle to v0.25.0
```
=> Update common-templates to v0.25.0

README.md, docs/development.md
Add information about the new vm-console-proxy operand.
```release-note
None
```
=> docs: add info about vm-console-proxy

Makefile
/cc @akrejcir 
/cc @codingben 
/cc @0xFelix 
Additional `ginkgo` and `getginkgo` targets are also introduce to help with updating and vendoring ginkgo in the future. They also ensure the expected version is present before running func tests.
Fixes #
```release-note
NONE
```
=> functest: Switch to calling ginkgo using go run

automation/common/deploy-kubevirt-and-cdi.sh
The CI script will use the released Kubevirt CR,
and then patch it to enable required functionality.
**Fixes**:
https://github.com/kubevirt/ssp-operator/issues/517
```release-note
None
```
=> chore: Use released Kubevirt CR in CI

OWNERS
Add @lyarwood to approvers.
```release-note
None
```
=> chore: Add lyarwood as approver to OWNERS

tests/dataSources_test.go, tests/misc_test.go
This is a manual backport of #441 to release-v0.16.
Applying these patches was missed during the release of v0.16.
```release-note
None
```
=> [release-v0.16] Cleanup fixes for tests waiting for DVs to succeed 

config/manager/manager.template.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, data/tekton-tasks/kubevirt-tekton-tasks-kubernetes.yaml, data/tekton-tasks/kubevirt-tekton-tasks-okd.yaml, hack/csv-generator.go, hack/csv-generator_test.go, internal/common/environment.go, internal/common/environment_test.go, internal/operands/tekton-tasks/tekton-tasks.go
feat: adjust tekton container links
This change replaces all tekton tasks containers with 2 new.
CSV generator was updated to accept only two links for tekton containers
Has to be merged after https://github.com/kubevirt/ssp-operator/pull/532
```
Update list of tekton containers
```
=> Update container list

.github/workflows/release-tekton-tasks.yaml, internal/common/version.go
fix: fix wrong version of tekton tasks containers
fix wrong version of tekton tasks containers and update release script to update version file.
```
NONE
```
=> fix: fix wrong version of tekton tasks containers

README.md
**What this PR does / why we need it**: The current description of the SSP operator should be updated to the current role of the ssp operator.
Fixes #
```release-note
None
```
=> docs: Improve description

go.mod
https://github.com/kubevirt/ssp-operator/actions/workflows/pull-request.yaml
This is running the hack/check-commited-changes.sh script and was previously failing due to uncommitted changes to go.mod.
Fixes #
```release-note
NONE
```
=> chore: Fix check_commited_files

config/samples/ssp_v1beta2_ssp.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Add vm-console-proxy annotations to the sample
of SSP CR.
```release-note
None
```
=> chore: add vm-console-proxy annotations

README.md, docs/configuration.md, docs/development.md, docs/installation.md
Improve SSP's docs readability and organize sections. The goal is to make simple, shorter and cleaner documentation.
- Improve readme.md
- Improve development.md
- Improve metrics.md
- Add installation.md
- Add configuration.md
```release-note
None
```
=> docs: improve SSP documentation

.github/workflows/validate-no-offensive-lang.yml, README.md, automation/e2e-upgrade-functests/run.sh, tests/TESTS.MD
This PR updates SSP master to main.
```
None
```
=> feat: Change ssp master to main

config/manifests/bases/ssp-operator.clusterserviceversion.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Update CSV description to be similar as we have
in README.md.
```release-note
None
```
=> chore: update CSV description

automation/e2e-upgrade-functests/run.sh
This code is not needed anymore after switching to main.
```
None
```
=> feat: Remove master branch option

OWNERS, OWNERS_ALIASES
This PR should automate  adding sradco to all monitoring PRs
```
None
```
=> feat: Add OWNERS_ALIASES and edit OWNERS file

.github/workflows/add-reviewer-monitoring.yaml
This PR should automate adding given users to monitoring PRs.
```
None
```
=> feat: Add github action that will add reviewer

data/tekton-pipelines/windows-bios-installer-pipeline.yaml, data/tekton-pipelines/windows-efi-installer-pipeline.yaml, internal/common/environment.go
Update virtio image version to v1.0.0
```release-note
chore: Update virtio image version to v1.0.0
```
=> chore: Update virtio image version to v1.0.0

go.mod, go.sum, vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go, vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go, vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go, vendor/modules.txt
Fixes #601
Just waiting on the final CDI release.
```release-note
NONE
```
=> chore: Move to kubevirt v1.0.0

data/common-templates-bundle/common-templates-v0.26.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.26.0 
```release-note
Update common-templates bundle to v0.26.0
```
=> Update common-templates to v0.26.0

controllers/setup.go
If `ssp-operator` deployment is created on a cluster without KubeVirt CRDs, it will crash and cause `CrashLoopBackoff` state. This PR prevents the creation on the VM controller if the KubeVirt CRDs are not installed.
Fixes https://github.com/kubevirt/ssp-operator/issues/682
```release-note
Do not register VM controller if KubeVirt CRDs are not installed
```
=> Do not register VM controller if KubeVirt CRDs are not installed

tests/common_instancetypes_test.go
/cc @codingben 
/cc @0xFelix 
Fixes #692 
```release-note
NONE
```
=> common-instancetypes: Wait until SSP is deployed during URI test

data/tekton-pipelines/windows-bios-installer-pipeline.yaml, data/tekton-pipelines/windows-efi-installer-pipeline.yaml, internal/common/environment.go
Update virtio image version to v1.0.1
```release-note
chore: Update virtio image version to v1.0.1
```
=> chore: Update virtio image version to v1.0.1

internal/operands/data-sources/reconcile_test.go
Restore a test that got deleted by accident in
de115ba7e020d08719baecb963df78ade839f0b6.
Fixes #
```release-note
None
```
=> reconcile: Restore test that go deleted by accident

internal/operands/data-sources/reconcile_test.go
Extend the test that ensures DataSources are not restored when a DataImportCron is present into a table with a PVC and a Snapshot entry.
Fixes #
See https://github.com/kubevirt/ssp-operator/pull/731 for context
```release-note
None
```
=> reconcile_test: Extend DataSource / DataImportCron restore test

.snyk
feat: add .snyk file
This file is used for excluding vendor folders from snyk code scans
```release-note
NONE
```
=> [release-v0.18]feat: add .snyk file

tests/monitoring_test.go
Adding polarion ID to identify the test for VirtualMachineCRCErrors test.
Fixes #
```release-note
NONE
```
=> adding polarion Id for VirtualMachineCRCErrors test

data/crd/ssp.kubevirt.io_ssps.yaml
Run `make container-build` to regenerate CRD.
```release-note
None
```
=> chore: Regenerate CRD

data/tekton-pipelines/windows-bios-installer-pipeline.yaml, data/tekton-pipelines/windows-efi-installer-pipeline.yaml, internal/common/environment.go
Update virtio image version to v1.1.0
```release-note
chore: Update virtio image version to v1.1.0
```
=> chore: Update virtio image version to v1.1.0

data/common-templates-bundle/common-templates-v0.27.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.27.0 
```release-note
Update common-templates bundle to v0.27.0
```
=> Update common-templates to v0.27.0

data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml, data/tekton-tasks/okd/kubevirt-tekton-tasks-okd.yaml, internal/common/version.go
chore: update tekton-tasks manifests to v0.15.1
```
chore: update tekton-tasks manifests to v0.15.1
```
=> [release-v0.18] chore: update tekton-tasks manifests to v0.15.1

data/tekton-pipelines/windows-bios-installer-pipeline.yaml, data/tekton-pipelines/windows-efi-installer-pipeline.yaml, internal/common/environment.go
Update virtio image version to v1.1.1
```release-note
chore: Update virtio image version to v1.1.1
```
=> chore: Update virtio image version to v1.1.1

internal/operands/data-sources/reconcile.go, internal/operands/data-sources/reconcile_test.go
We hit this in previous versions, and think it may make sense to cherry pick, let us know what you think!
Fixes #
```release-note
fix: Incorrect DataSource reconciliation
```
=> [release-v0.18] fix: Incorrect DataSource reconciliation

internal/operands/metrics/resources.go, tests/monitoring_test.go
This is a manual cherry-pick of https://github.com/kubevirt/ssp-operator/pull/875
jira-ticket: https://issues.redhat.com/browse/CNV-35099
Fixes #
```release-note
Rename VirtualMachineCRCErrors to VMStorageClassWarning
```
/cc @0xFelix @codingben @jcanocan
=> [release-v0.19] Rename VirtualMachineCRCErrors to VMStorageClassWarning

tests/monitoring_test.go
https://github.com/kubevirt/ssp-operator/pull/907#discussion_r1512989745
Fixes #
```release-note
none
```
=> Adjust VMStorageClassWarning E2E MatchError timeout

tests/monitoring_test.go
address failures such as https://main-jenkins-csb-cnvqe.apps.ocp-c1.prod.psi.redhat.com/job/test-ssp-cnv-4.14/
Fixes #
```release-note
none
```
=> Replace test 'Eventually-Consistently' with 'Eventually-MustPassRepeatedly

data/common-templates-bundle/common-templates-v0.29.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.29.0 
```release-note
Update common-templates bundle to v0.29.0
```
=> Update common-templates to v0.29.0

data/common-templates-bundle/common-templates-v0.29.1.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.29.1 
```release-note
Update common-templates bundle to v0.29.1
```
=> Update common-templates to v0.29.1

data/common-templates-bundle/common-templates-v0.29.2.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.29.2 
```release-note
Update common-templates bundle to v0.29.2
```
=> Update common-templates to v0.29.2

data/common-templates-bundle/common-templates-v0.29.3.yaml, internal/operands/common-templates/version.go, renovate.json
Update common-templates bundle to v0.29.3 
```release-note
Update common-templates bundle to v0.29.3
```
=> Update common-templates to v0.29.3

renovate.json
chore: enable gomodTidy in renovate
```
NONE
```
=> chore: enable gomodTidy in renovate

validator.Dockerfile
Fixes #
```release-note NONE
```
=> feat: multiarch compatibility to validator.Dockerfile

data/common-templates-bundle/common-templates-v0.31.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.31.0 
```release-note
Update common-templates bundle to v0.31.0
```
=> Update common-templates to v0.31.0

data/common-templates-bundle/common-templates-v0.31.1.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to version v0.31.1
```
Update common-templates bundle to version v0.31.1
```
=> [release-v0.21] Update common-templates bundle to version v0.31.1

internal/operands/metrics/resources.go, tests/monitoring_test.go
This version is widely used, so we are updating the alert name to match the published runbooks and support material
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-44991
```release-note
Rename VirtualMachineCRCErrors to VMStorageClassWarning
```
=> Rename VirtualMachineCRCErrors to VMStorageClassWarning

data/common-templates-bundle/common-templates-v0.29.4.yaml, internal/operands/common-templates/version.go
Fixes #
```release-note
Update common-templates bundle to v0.29.4
```
=> Update common-templates bundle to version v0.29.4

tests/crypto_policy_test.go
The current code in functional tests that loads root CA for TLS connection to template-validator does not work when SSP is deployed by OLM.
This commit is a simple fix, where we ignore the validity of the certificate passed by template-validator. This is ok for these tests, because different tests that check behavior of the template-validator would fail if the certificate was invalid.
Fixes: https://issues.redhat.com/browse/CNV-47164
```release-note
None
```
=> tests: TLS policy: Use insecure TLS for connection to template-validator

go.mod, go.sum, pkg/monitoring/rules/alerts/prometheus.go, pkg/monitoring/rules/recordingrules/recordingrules.go, pkg/monitoring/rules/rules.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector_result.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/counter.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/counter_vec.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/gauge.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/gauge_vec.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram_vec.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/metric.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary_vec.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/wrapper_registry.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/compatibility.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/prometheusrules.go, vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/registry.go, vendor/modules.txt
It updates the operator version and includes the required changes for avoiding the usage of deprecated functions.
Fixes #
```release-note
None.
```
=> chore(observability): Bump operator observability version 0.0.24

data/common-templates-bundle/common-templates-amd64-v0.32.2.yaml, data/common-templates-bundle/common-templates-s390x-v0.32.2.yaml, data/common-templates-bundle/common-templates-v0.32.2.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.32.2 
```release-note
Update common-templates bundle to v0.32.2
```
=> Update common-templates to v0.32.2

data/common-templates-bundle/common-templates-v0.27.1.yaml, internal/operands/common-templates/version.go
Fixes #
```release-note
Update common-templates bundle to v0.27.1
```
=> Update common-templates bundle to version v0.27.1

Makefile
Bump golangci-lint 1.62.2
Fixes #
```release-note
None
```
=> chore(golangci-lint): Bump golangci-lint 1.62.2

internal/template-bundle/bundle.go, internal/template-bundle/template-bundle-test.yaml
This change simplifies the parsing process by reducing complexity.
Fixes #
```release-note
NONE
```
=> refactor: use the template architecture label

internal/common/resource.go
The error messages now contain the type, name and namespace of the object that failed. The error is then propagated to the `.status.conditions` of the SSP object.
Jira: https://issues.redhat.com/browse/CNV-48792
```release-note
None
```
=> feat: Improve errors returned from reconciliation

automation/common/versions.sh
Fixes CDI version for this release branch.
```release-note
None
```
=> [release-v0.21] CI: Fix CDI version

tests/port-forwarding.go
We can use the data stream directly, instead of using a net.Pipe to copy data to and from it.
```release-note
None
```
=> cleanup: Remove net.Pipe in port-forwarding in functests

internal/operands/metrics/resources.go, tests/monitoring_test.go
This is a manual cherry-pick of https://github.com/kubevirt/ssp-operator/pull/1126
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-56875
```release-note
Alert VMStorageClassWarning only for Windows VMs
```
=> Alert VMStorageClassWarning only for Windows VMs

data/common-templates-bundle/common-templates-amd64-v0.33.0.yaml, data/common-templates-bundle/common-templates-s390x-v0.33.0.yaml, data/common-templates-bundle/common-templates-v0.33.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.33.0 
```release-note
Update common-templates bundle to v0.33.0
```
=> Update common-templates to v0.33.0

data/common-templates-bundle/common-templates-amd64-v0.34.0.yaml, data/common-templates-bundle/common-templates-arm64-v0.34.0.yaml, data/common-templates-bundle/common-templates-s390x-v0.34.0.yaml, data/common-templates-bundle/common-templates-v0.34.0.yaml, internal/operands/common-templates/version.go
Update common-templates bundle to v0.34.0 
```release-note
Update common-templates bundle to v0.34.0
```
=> Update common-templates to v0.34.0

config/manager/manager.template.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/operands/template-validator/resources.go, internal/operands/vm-console-proxy/reconcile.go
Ensure all containers use FallbackToLogsOnError in TerminationMessagePolicy.
Jira-Url: https://issues.redhat.com/browse/CNV-58257
```release-note
None
```
=> feat(CNV-58257): set terminationMessagePolicy in all containers

tests/vm_delete_protection_test.go
Adding test_id's and add additional test case to explictly check 
https://issues.redhat.com/browse/CNV-50739
Fixes #
```release-note
None
```
=> Add polarion test id's

Dockerfile, api/go.mod, go.mod, validator.Dockerfile, vendor/modules.txt
Update go version to 1.24.3
Fixes #
```release-note
None
```
=> chore(update-go): Update go version to 1.24.3

automation/e2e-functests/run.sh, config/rbac/role.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, hack/csv-generator_test.go, hack/install-network-policy.sh, hack/sync.sh, internal/common/resource.go, internal/controllers/setup.go, internal/networkpolicies/networkpolicies.go, internal/operands/data-sources/reconcile.go, internal/operands/data-sources/reconcile_test.go, internal/operands/data-sources/resource.go, internal/operands/template-validator/reconcile.go, internal/operands/template-validator/reconcile_test.go, internal/operands/template-validator/resources.go, internal/operands/vm-console-proxy/reconcile.go, internal/operands/vm-console-proxy/reconcile_test.go, tests/dataSources_test.go, tests/validator_test.go, tests/vm_console_proxy_test.go
Deploy network policies for the components deployed by SSP so they can work in a locked down environment. As preparation install a default deny NetworkPolicy before running functional tests. 
Fixes https://issues.redhat.com/browse/CNV-59257
Based on #1458, merge first
```release-note
Deploy network policies for the components deployed by SSP
```
=> feat: Deploy network policies

main.go
Followup PR to #640. Avoids a goroutine leak in the event of server.ListenAndServeTLS() returning an error.
Fixes #667 
```release-note
NONE
```
=> fix: clean up goroutines on error

config/manager/manager.template.yaml, internal/operands/template-validator/resources.go
Update the resources requested by SSP  and virt-template-validator to better match with the consumed resources that were observed on a live cluster.
Fixes #
```release-note
None
```
=> Update resources of SSP and virt-template-validator

data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Previous PR did not regenerate CSV. Run `make container-build` to regenerate all files.
```release-note
None
```
=> chore: Regenerate CSV

data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Regenerated file using `make container-build`.
```release-note
None
```
=> chore: regenerated file using "make container-build"
