.travis.yml, Makefile, internal/operands/metrics/resources.go, tests/metrics_test.go, tests/tests_suite_test.go
The tests assume that ssp-operator is running, either in the cluster or outside.
=> Add functional tests for metrics operand.

controllers/ssp_controller.go, internal/common/resource.go, internal/common/resource_test.go, internal/operands/metrics/reconcile.go, internal/operands/metrics/reconcile_test.go, internal/operands/template-validator/reconcile.go, internal/operands/template-validator/reconcile_test.go, tests/validator_test.go
Some of the current code reimplements logic from `controller-runtime` library. This PR uses the library code instead.
When writing the code, I did not notice that similar functions already exist in the library.
=> Use controller runtime methods

controllers/ssp_controller.go
Multiple operands may need to watch the same resource.
This patch checks the types of the resources and only
adds watch once for each type.
```release-note
NONE
```
=> Do not watch the same resource multiple times

Makefile, README.md, controllers/ssp_controller.go, internal/operands/template-validator/reconcile.go
Temporarily skip building tests in a container until OCP CI is ready.
It will simplify testing CI scripts.
```release-note
NONE
```
=> Temporarily skip build container

api/v1alpha1/ssp_types.go, api/v1alpha1/ssp_webhook.go, api/v1alpha1/ssp_webhook_test.go, config/crd/bases/ssp.kubevirt.io_ssps.yaml, tests/webhook_test.go
Added validations to the API and webhook
In API:
- `templateValidator.replicas` cannot be negative
- `commonTemplates.namespace` must be valid namespace
In webhook:
- `commonTemplates.namespace` cannot be updated on existing CR
```release-note
NONE
```
=> Add validations to the API and webhook

controllers/ssp_controller.go, go.mod, internal/common/cache.go, internal/common/request.go, internal/common/resource.go, internal/common/resource_test.go, internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go, internal/operands/metrics/reconcile.go, internal/operands/metrics/reconcile_test.go, internal/operands/node-labeller/reconcile.go, internal/operands/node-labeller/reconcile_test.go, internal/operands/operand.go, internal/operands/template-validator/reconcile.go, internal/operands/template-validator/reconcile_test.go, tests/commonTemplates_test.go, tests/metrics_test.go, tests/nodeLabeller_test.go, tests/tests_common_test.go, tests/tests_suite_test.go, tests/validator_test.go, tests/watcher.go, tests/webhook_test.go
Added `status` field to the SSP CR.
`status.phase` can be used to check if the SSP operator finished deployment of all dependent resources.
`status.conditions` give more information about the status.
```release-note
Added status to the SSP resource.
```
=> Add status phase and conditions

internal/operands/template-validator/resources.go, tests/validator_test.go
Signed-off-by: Shweta Padubidri <spadubid@redhat.com>
Reconcile the exact same resources as the old operator to provide zero interruption upgrade
Fixes #
```release-note
None
```
=> Reconcile the exact same resources as the old operator

Makefile
Openshift CI containers may not include 'kubectl' binary, so the makefile uses 'oc' instead.
```release-note
NONE
```
=> Makefile uses 'oc' or 'kubectl' depending on which one is available

hack/csv-generator.sh
add missing divider between deployment and crds
```NONE
```
=> [FIX] add missing divider between deployment and crds

Makefile, internal/common/environment.go, tests/tests_suite_test.go, tests/validator_test.go
This PR fixes a race condition, when the deployment of the operator is too slow.
```release-note
NONE
```
=> Functests wait for operator deployment

config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/default/manager_webhook_patch.yaml, config/manager/manager.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/auth_proxy_service.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/webhook/manifests.v1beta1.yaml, config/webhook/service.yaml
Change default namespace for operator pod
Fixes #
```release-note
NONE
```
=> Change default namespace for operator pod

tests/commonTemplates_test.go, tests/metrics_test.go, tests/nodeLabeller_test.go, tests/tests_common_test.go, tests/tests_suite_test.go, tests/validator_test.go, tests/webhook_test.go
Added an option to run functional tests with an existing SSP CR.
This patch adds these environment variables:
- `TEST_EXISTING_CR_NAME` - Name of the SSP CR
- `TEST_EXISTING_CR_NAMESPACE` - Namespace of the SSP CR
- `SKIP_UPDATE_SSP_TESTS` - If `true`, tests that modify the SSP CR are skipped. This is useful if another controller watches the CR and reverts any changes
If `TEST_EXISTING_CR_NAME` is not defined, the tests create a new SSP CR.
```release-note
NONE
```
=> Run functional tests with existing SSP CR

api/v1beta1/ssp_webhook.go, api/v1beta1/ssp_webhook_test.go, tests/tests_suite_test.go, tests/webhook_test.go
Webhook validates that namespace set in `commonTemplates.namespace` exists.
```release-note
NONE
```
=> Validate that namespace for common templates exists

Makefile, api/v1beta1/ssp_webhook.go, config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/default/manager_webhook_patch.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/manifests/bases/ssp-operator.clusterserviceversion.yaml, config/namespace/kustomization.yaml, config/namespace/namespace.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/kustomization.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml, config/samples/ssp_v1beta1_ssp.yaml, config/webhook/kustomization.yaml, config/webhook/manifests.v1beta1.yaml, config/webhook/service.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml
The default names generated by operator-sdk may collide with other operators created using the SDK
```release-note
NONE
```
This PR uses code from PR: #51
=> Change resource names used by operator

.travis.yml
The unit tests are currently run by OCP CI
```release-note
NONE
```
=> Remove unit tests from TravisCI

controllers/ssp_controller.go, internal/common/cache.go, internal/common/request.go, internal/common/resource.go, internal/common/resource_test.go, internal/operands/common-templates/reconcile.go, internal/operands/metrics/reconcile_test.go, internal/operands/template-validator/reconcile.go, internal/operands/template-validator/reconcile_test.go, tests/tests_common_test.go, tests/tests_suite_test.go, tests/validator_test.go
Since Openshift `4.6` and Kubernetes `v1.19.0`, a status change on SSP CR causes reconciliation.
This patch adds a predicate to ignore the status change, otherwise the operator would never stop with reconciliation.
```release-note
NONE
```
=> Break infinite reconciliation loop

data/common-templates-bundle/common-templates-v0.13.0-rc.0.yaml, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.13.0-rc.0.yaml, internal/operands/common-templates/resource.go, tests/commonTemplates_test.go
Signed-off-by: Kevin Wiesmueller <kwiesmul@redhat.com>
Manually updates the common-templates bundle until https://github.com/kubevirt/common-templates/issues/293 is resolved.
The update is required for https://github.com/kubevirt/ssp-operator/pull/63 to succeed.
Based on the file from https://github.com/kubevirt/kubevirt-ssp-operator/pull/259.
```release-note
Updated common templates to v0.13.0-rc.0
```
=> Update the common-templates bundle to v0.13.0-rc.0

controllers/ssp_controller.go
Fixed a condition that caused operator verison to default to 'devel' when it was actually provided
```release-note
None
```
=> Fixed operator version assignment

tests/webhook_test.go
Webhook tests were failing due to attempts to create SSP resources with metadata.resourceVersion defined.
This commit makes sure no existing object metadata is leftover on creation
```release-note
None
```
=> Fix webhook tests that create resources with irrelevant metadata

controllers/ssp_controller.go, internal/common/resource.go, internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go, tests/commonTemplates_test.go, tests/tests_suite_test.go
The operator will now replace the ownerReferences on older templates with owner annotations pointing to the SSP CR that is reconciling them to prevent them from being removed when their old owner is deleted.
We need this PR to make sure that existing templates are not deleted from the cluster when the old CR is being removed
```release-note
None
```
=> Replace owner references with owner annotations for previously deployed templates during an upgrade

internal/common/resource.go
On a previos change I presented (#72), I mistakingly used `Patch` which was over complicated
```release-note
None
```
=> Remove owner references for older templates with and Update api call instead of a Patch

api/v1beta1/ssp_types.go, config/crd/bases/ssp.kubevirt.io_ssps.yaml, controllers/ssp_controller.go, data/crd/ssp.kubevirt.io_ssps.yaml, tests/commonTemplates_test.go, tests/metrics_test.go, tests/nodeLabeller_test.go, tests/tests_common_test.go, tests/tests_suite_test.go, tests/validator_test.go
When debugging the deployment, it can be useful to pause the operator.
The reconciliation can be paused by adding annotation:
`"kubevirt.io/operator.paused": "true"`
```release-note
NONE
```
=> Add paused annotation

internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go, tests/commonTemplates_test.go
remove workload, flavor, os labels from templates which have older version
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=1859235
```release-note
SSP operator now removes workload, flavor, os labels from templates which have older version
```
=> Remove workload, flavor, os labels from templates which have older version

tests/commonTemplates_test.go, tests/tests_suite_test.go
Add environment vars to allow modification of test timeouts
```release-note
None
```
=> Add support for environment vars to modify test timeouts

internal/operands/common-templates/resource.go, tests/commonTemplates_test.go, tests/tests_common_test.go, tests/tests_suite_test.go
Makes the `kubevirt-os-images` namespace visible for regular users with `oc projects`.
This enables UI users to clone images from this namespace
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1893278
```release-note
kubevirt-os-images namespace is now visible to all users
```
=> [Bugfix] Make kubevirt-os-images visible to regular users

internal/operands/common-templates/resource.go, tests/commonTemplates_test.go, tests/tests_common_test.go
Allows regular users to view DataVolumes in the os-images namespace, main usecase is to follow the upload status of the image
**Which issue(s) this PR fixes** 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1913717
```release-note
None
```
=> [Bugfix] Give regular users permissions to view os images DataVolumes

tests/commonTemplates_test.go, tests/tests_common_test.go
Reuse code in the os-images namespace permission tests, this is based on #83 , so it should only be merged after it
```release-note
None
```
=> Make os images tests more aesthetic

tests/commonTemplates_test.go
The centos6 templates do not exist downstream, which causes tests to fail, so let's use rhel instead
```release-note
NONE
```
=> Use a rhel8 template during testing instead of centos6

tests/e2e-test-csv-generator.sh
csv-generator test now points to the right binary path inside the container and will fail CI if errors occurred
```release-note
None
```
=> Fix csv-generator test

api/v1beta1/ssp_types.go, config/crd/bases/ssp.kubevirt.io_ssps.yaml, controllers/ssp_controller.go, data/crd/ssp.kubevirt.io_ssps.yaml, tests/misc_test.go, tests/tests_suite_test.go
The `observedGeneration` field can be used to check if the operator has seen latest changes to the SSP resource.
```release-note
Added 'status.observed_generation' field.
```
=> Add observedGeneration to the SSP status

Makefile
Build and attach the test binary to a release to make it accessible for QE downstream
```release-note
NONE
```
=> Build and attach the test binary to a release

automation/ocp-ci-run-e2e-upgrade-tests.sh, automation/ssp-cr-template.yaml
Created a script to test upgrade from the latest released version.
```release-note
None
```
=> Add a script for upgrade testing used by OCP CI

config/manager/manager.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, main.go
Added readiness probe to the operator pod to signal when the webhook is ready to receive requests.
```release-note
None
```
=> Add readiness probe to the operator pod

automation/ocp-ci-run-e2e-upgrade-tests.sh
The master version of operator uses readiness probe, but the upgrade test deploys the latest released version, which does not yet have the probe.
```release-note
None
```
=> Temporarily add sleep to upgrade test

tests/commonTemplates_test.go, tests/tests_common_test.go
Add RBAC tests for OS Images from the old operator functests https://github.com/kubevirt/kubevirt-ssp-operator/blob/master/functests/12-test-os-imaes-namespace_rbac.sh
Fixes #
```release-note
Add RBAC tests for OS Images
```
=> Add RBAC tests for OS Images

automation/ssp-cr-template.yaml, controllers/ssp_controller.go, go.mod, internal/common/labels.go, internal/common/labels_test.go, internal/operands/common-templates/reconcile.go, internal/operands/metrics/reconcile.go, internal/operands/node-labeller/reconcile.go, internal/operands/template-validator/reconcile.go, tests/commonTemplates_test.go, tests/labels_test.go, tests/metrics_test.go, tests/nodeLabeller_test.go, tests/tests_common_test.go, tests/tests_suite_test.go, tests/validator_test.go, vendor/modules.txt
This PR adds the [kubernetes app labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) to all resources maintained by the operator.
We are adding:
```
app.kubernetes.io/name: <name of the operand>
app.kubernetes.io/version: <version of the CSV (more details below)>
app.kubernetes.io/component: <component in the overall architecture this belongs to>
app.kubernetes.io/part-of: <name of the entire deployment (more details below)>
app.kubernetes.io/managed-by: "ssp-operator"
```
The values for `app.kubernetes.io/version` and `app.kubernetes.io/part-of` should be provided by HCO as they are based on the CSV.
To get those values when reconciling resources, we look at the SSP CR and extract those two labels from …
=> Add app.kubernetes.io labels to resources provisioned by ssp-operator

internal/operands/node-labeller/defaults.go
Update node-labeller to pull virt-launcher image from quay, and also bumped virt-launcher to the latest release
Dockerhub's pull policy limitations prevents node-labeller from properly deploying for upstream users
```release-note
None
```
=> Update node-labeller to pull virt-launcher image from quay

hack/csv-generator.go, internal/operands/node-labeller/defaults.go, internal/operands/node-labeller/resources.go
csv-generator now computes and populates proper `relatedImages` for the CSV
```release-note
The relatedImages spec field is now populated and image caching should be supported
```
=> csv-generator: populate spec.relatedImages

internal/common/resource.go, internal/common/resource_test.go, internal/operands/common-templates/reconcile.go, internal/operands/metrics/reconcile.go, internal/operands/node-labeller/reconcile.go, internal/operands/template-validator/reconcile.go
There are four `CreateAndUpdate` methods with various parameters. This patch creates a builder to use instead of these functions.
```release-note
NONE
```
=> Create a builder for reconcile methods

internal/operands/node-labeller/resources.go, internal/operands/template-validator/resources.go
Created resources could be modified during reconciliation, which would modify global instances of objects.
```release-note
NONE
```
=> Remove global variables from resource objects

Makefile, README.md
Currently the dnf installs v2 of kustomize by default which fails the build.
Added a note about installing a newer version.
Signed-off-by: borod108 <bodnopoz@redhat.com>
```release-note
NONE
```
=> Add remark on kustomize version

internal/operands/common-templates/constants.go, internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go, internal/operands/common-templates/resource.go, tests/commonTemplates_test.go
- Extracts common label strings to constants.
- Simplifies API calls that use label selector.
Fixes issues found by SonarCloud.
```release-note
None
```
=> Extract label strings and simplify API calls with label selector

internal/operands/common-templates/constants.go, internal/operands/common-templates/version.go
The `Version` is changed by common-templates release script. Moving it to separate file is safer.
```release-note
None
```
=> Move common-templates version to separate file

internal/operands/common-templates/constants.go, internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go
During reconcilation ssp operator now adds deprecated label to old
templates
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1925019
```
Operator now adds `template.kubevirt.io/deprecated` label to old templates
```
=> add deprecated label to old templates

api/v1beta1/ssp_webhook.go, config/default/webhook_ocp_cainjection_patch.yaml, config/default/webhookcainjection_patch.yaml, config/webhook/kustomization.yaml, config/webhook/manifests.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Update webhook version to `admissionregistration.k8s.io/v1`. The `v1beta1` version will be removed in kubernetes 1.22
```release-note
Updated webhook version to admissionregistration.k8s.io/v1`
```
=> Update webhook version to admissionregistration.k8s.io/v1

internal/operands/template-validator/resources.go
Added rule to `ValidatingWebhookConfiguration` of template validator to be called also for `v1` version of `VirtualMachine`.
**Which issue(s) this PR fixes** :
https://bugzilla.redhat.com/show_bug.cgi?id=1936926
```release-note
Set template validator webhook to receive v1 versions of VirtualMachines.
```
=> Template validator webhook rule for v1 VMs

internal/operands/node-labeller/defaults.go, internal/operands/node-labeller/reconcile.go, internal/operands/node-labeller/reconcile_test.go, internal/operands/node-labeller/resources.go, tests/nodeLabeller_test.go
**Do not merge. Work in progress. It is missing upgrade test**
ssp operator deletes the node-labeller
This PR updates the reconcile function for node-labeller,
so now it instead of creating/updating deletes all components of labeller.
```
SSP operator now deletes all node-labeller components, because labeller was moved into Kubevirt.
```
=> ssp operator deletes the node-labeller

internal/operands/common-templates/constants.go, internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go, tests/commonTemplates_test.go
move deprecated label to annotations
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1925019
```
NONE
```
=> move deprecated label to annotations

internal/operands/template-validator/resources.go
Added rule to `ValidatingWebhookConfiguration` of template validator to be called also for `v1` version of `VirtualMachine`.
https://bugzilla.redhat.com/show_bug.cgi?id=1936926
```release-note
Set template validator webhook to receive v1 versions of VirtualMachines.
```
=> (v0.1) Template validator webhook rule for v1 VMs

internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go, tests/commonTemplates_test.go
backport deprecated annotation
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1925019
```
NONE
```
=> backport deprecated annotation

api/v1beta1/ssp_webhook.go, tests/webhook_test.go
This PR adds a deployment creation dry-run to the SSP webhook to reject any invalid placement fields.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1938241
- Still missing tests
```release-note
None
```
=> Add a dry-run to verify placement fields

hack/csv-generator.go
CRD should not contain the `relatedImages` field.
Fixes #143
Remove the `relatedImages` field from the CRD.
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
```release-note
NONE
```
=> Remove the relatedImages field from the CRD

config/crd/patches/webhook_in_ssps.yaml
The config was generated by operator SDK and is currently not used, but it may be used in the future.
Updating its API in case we use it.
```release-note
None
```
=> Update API version in unused config file

internal/operands/metrics/resources.go
Signed-off-by: Shirly Radco <sradco@redhat.com>
Add os, workload and flavor labels to
cnv:vmi_status_running:count metric.
Fixes #
Check that the cnv:vmi_status_running:count metric, for vms that were created by a template (templates should include the os, flavor and workload annotations), is aggregated by node, os, workload and flavor labels.
```release-note
NONE
```
=> Update cnv:vmi_status_running:count labels

README.md
The names of some environment variables have changed, updating readme
accordingly.
```release-note
NONE
```
=> Fix readme for building with custom image

Makefile, internal/template-validator/Dockerfile, validator.Dockerfile
This enables openshift CI to use the new Dockerfile for template-validator and build the template-validator container from the latest source code
Fixes the CI errors for https://github.com/openshift/release/pull/18098 
```release-note
NONE
```
=> Add build process to validator Dockerfile

.gitignore, Makefile, config/manager/manager.template.yaml, internal/operands/template-validator/reconcile.go
Fixes #
```release-note
NONE
```
=> Changes to inject template-validator image to ssp-operator build

.github/workflows/release.yaml, Makefile
This adds the release automation needed to publish container images for template-validator when we do a release for ssp-operator 
Also, this will change the versioning for template-validator images to one equal to ssp-operator release 
Fixes #
```release-note
NONE
```
=> Add release automation for template-validator

config/manager/manager.template.yaml, internal/operands/template-validator/resources.go
This adds a `priorityClassName` to the ssp-operator & template-validator pod spec
More about priorityclasses: https://docs.openshift.com/container-platform/4.7/nodes/pods/nodes-pods-priority.html
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1953483
```release-note
NONE
```
=> Add priorityClassName to ssp-operator pod

config/manager/manager.template.yaml, internal/operands/template-validator/resources.go
Add resource requests to ssp-operator and template-validator containers
Following the Openshift [CONVENTIONS](https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits), no limits are set, keeping in mind that recourse needs would grow as the cluster grows 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1953485
```release-note
NONE
```
=> Add Resource requests to pods

config/manager/manager.template.yaml, internal/operands/template-validator/resources.go
Add resource requests to ssp-operator and template-validator containers
Following the Openshift [CONVENTIONS](https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits), no limits are set, keeping in mind that recourse needs would grow as the cluster grows 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1953485
```release-note
NONE
```
=> [v0.2] Add Resource requests to pods

internal/operands/template-validator/resources.go, internal/template-validator/webhooks/hook.go
The `ValidatingWebhookConfiguration` uses `v1` admission review version.
Added missing fields to `AdmissionReview` response. Without them, k8s will reject the response.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1936926
```release-note
None
```
=> Update webhook version for template validator to v1

internal/operands/template-validator/resources.go, internal/template-validator/webhooks/hook.go
The `ValidatingWebhookConfiguration` uses `v1` admission review version.
Added missing fields to `AdmissionReview` response. Without them, k8s will reject the response.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1936926
```release-note
None
```
=> [v0.11] Update webhook version for template validator to v1

hack/csv-generator.go
The csv-generator does not override environment variables `VALIDATOR_IMAGE` and `OPERATOR_VERSION`, if no override flag is specified on the command line.
```release-note
None
```
=> csv-generator: Override environment variables only when needed

Dockerfile, Makefile, internal/operands/template-validator/defaults.go
Update the template validator image deployed by the SSP operator to the
latest released one on every release.
The default template validator image should no longer be manually updated for each release
```release-note
NONE
```
/cc @akrejcir @kwiesmueller
=> Update the default template-validator image to the latest released one

internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go
fixed deprecated label which is set during upgrade to up-to-date template
When deprecated label is set to old templates and new templates are deployed with the same name, during update the deprecated label stays on updated template. 
This patch updates the behaviour, so at first it loads all templates which will be deployed and then it applies deprecated label only to templates which will not be updated.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1964583
```
NONE
```
=> fixed deprecated label which is set during upgrade to up-to-date template

.github/workflows/validate-no-offensive-lang.yml, Makefile, automation/ocp-ci-run-e2e-upgrade-tests.sh, hack/validate-no-offensive-lang.sh
Add a check to the sannity test that fails if there is a usage
of offensive language in one of the files.
The script forbit the use of the words `master`, `slave`,
`blacklist` and `whitelist`
Sinse `master` is very common word as a name of default
branches or as a node name in clusters, the script allows
the usage of it if this word is part of a URL or a path.
The script does not check several directories that may
contain third party usage of the word `master`:
`vendor/` `deploy/` and `cluster`.
Fixes #
```
NONE
```
=> Validate that this repository does not contain offensive language

Dockerfile, validator.Dockerfile
switch base image from golang-1.15 to ubi8/ubi-minimal
Due to pull rate limit from docker hub our tests constantly fails.
This PR switches main docker image to ubi8 image.
@akrejcir @kwiesmueller @omeryahud @vatsalparekh @dominikholler WDYT about this change?
```
NONE
```
=> switch base image from golang-1.15 to ubi8/ubi-minimal

Dockerfile, Makefile, data/olm-catalog/ssp-operator.clusterserviceversion.yaml
The `VERSION` variable in `Makefile` should be equal to the next release version in the sequence.
A file was not copied to the builder image in `Dockerfile`. It produces an error message, that is currently ignored, but when the operator-sdk will be updated, it will cause the build to fail.
Regenerated CSV in data/olm-catalog.
```release-note
None
```
=> Fix VERSION variable in Makefile, fix Dockerfile, update CSV

tests/commonTemplates_test.go, tests/labels_test.go, tests/tests_common_test.go, tests/tests_suite_test.go, tests/validator_test.go
- Use `GenerateName` to create unique temporary resources for tests. This helps with timing issues, when a temporary resource from one test was not yet deleted and is used by a different test.
- Template validator tests wait until new templates propagate to template validator.
- Make test failures more verbose
```release-note
None
```
=> Stabilize functional tests

Makefile
I forgot to remove the `TODO` in my previous PR.
```release-note
None
```
=> Remove a TODO comment from Makefile

automation/e2e-functests/run.sh, automation/e2e-functests/setup.sh, automation/e2e-upgrade-from-old-operator-functests/run.sh, automation/e2e-upgrade-from-old-operator-functests/setup.sh, automation/e2e-upgrade-functests/run.sh, automation/e2e-upgrade-functests/setup.sh
The test scripts from OCP CI jobs are moved to this repository. Then CI jobs for different branches can be merged into a single job.
```release-note
None
```
=> Move test scripts from OCP CI jobs to automation directory

automation/e2e-functests/run.sh, automation/e2e-functests/setup.sh, automation/e2e-upgrade-from-old-operator-functests/run.sh, automation/e2e-upgrade-from-old-operator-functests/setup.sh, validator.Dockerfile
The test scripts from OCP CI jobs are moved to this repository. Then CI jobs for different branches can be merged into a single job.
```release-note
None
```
=> [release-v0.1] Move test scripts from OCP CI jobs to automation directory

automation/e2e-functests/run.sh, automation/e2e-functests/setup.sh, automation/e2e-upgrade-from-old-operator-functests/run.sh, automation/e2e-upgrade-from-old-operator-functests/setup.sh
The test scripts from OCP CI jobs are moved to this repository. Then CI jobs for different branches can be merged into a single job.
```release-note
None
```
=> [release-v0.11] Move test scripts from OCP CI jobs to automation directory

Makefile, data/olm-catalog/ssp-operator.clusterserviceversion.yaml
The VERSION variable in makefile should be equal to the next release version in the sequence.
Regenerated CSV in data/olm-catalog.
```release-note
None
```
=> [v0.11] Fix VERSION variable in Makefile, and update CSV

api/v1beta1/ssp_webhook.go
Signed-off-by: Igor Bezukh <ibezukh@redhat.com>
It is possible to remove the `kubenetes` finalizer from `default` namespace and remove the namespace itself.
This PR suggests a bit safer approach to validate the placement configuration, using the namespace in which the SSP
CR was created.
My assumption is that the SSP CR and it's components are deployed in the same namespace, therefore there souldn't
be any RBAC issues with the dry-run. If it's not the case feel free to ignore the PR/
```release-note
NONE
```
=> [admission-webhook] Use namespace in which the SSP CR was created for the placement validation dry-run

internal/operands/metrics/resources.go
Implement monitoring conventions for the rule names,
add links from alerts to the runbooks.
The runbooks will be added later, these are just place holders.
```release-note
NONE
```
=> Fix recording rule names and add links to runbooks

config/manager/manager.template.yaml, tests/misc_test.go
Changing the security context on the deployment, changes the assigned SCC from `privileged` to `restricted`.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1995295
```release-note
None
```
=> Change securityContext on operator, so that scc is 'restricted'

go.mod
Golang version in the dockerfile is currently at 1.15 and can not be upgraded to 1.16 because UBI currently does not have it. Rolling the version back to 1.15 in go.mod to avoid any version conflicts.
```release-note
NONE
```
=> Rollback Golang version back to 1.15

internal/template-validator/webhooks/hook.go, tests/metrics_test_utils.go, tests/validator_test.go, vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go, vendor/modules.txt
Add a metrics to template_validator to monitor the number of rejected Vms
```release-note
The metrics endpoint at the template_validtor pods will now have a total_rejected_vms metrics that counts the number of Vms it rejected.
```
=> Add total_rejected_vms matrics

internal/operands/metrics/resources.go
Adding kubevirt_ssp_rejected_vms_total recording rule and
SSPHighRateRejectedVms alert to warn user in case many VMs
are being rejected.
```release-note
Added SSPHighRateRejectedVms Alert which will activate as a warning in case of high rate of rejected VMs
```
=> Recording rule and alert for SSPHighRateRejectedVms

config/manager/manager.template.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/operands/template-validator/resources.go
Added `name` label to `ssp-operator`, and `virt-template-validator` deployments and pods.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1998656
```release-note
None
```
=> Add "name" labels to deployments and pods

internal/template-validator/validation/eval.go, internal/template-validator/validation/eval_test.go, internal/template-validator/validation/path/conv.go, internal/template-validator/validation/path/path.go, internal/template-validator/validation/path/path_suite_test.go, internal/template-validator/validation/path/path_test.go, internal/template-validator/validation/path/variants.go, internal/template-validator/validation/path/variants_test.go, internal/template-validator/validation/rules.go, internal/template-validator/validation/rules_test.go, internal/template-validator/validation/specialized.go, internal/template-validator/validation/specialized_test.go, internal/template-validator/validation/test-utils/utils.go, internal/template-validator/webhooks/admission_test.go
This PR contains these code changes:
- Created `RuleType` type to emulate enum.
- Split `validation.Path` struct into 2 structs `Path` and `Results`
- `Rule` struct uses specific types instead of generic `string` and `interface{}`
```release-note
None
```
=> Code change: Improve validator code

controllers/ssp_controller.go, internal/common/resource.go, internal/common/resource_test.go, internal/operands/common-templates/reconcile.go, internal/operands/metrics/reconcile.go, internal/operands/node-labeller/reconcile.go, internal/operands/operand.go, internal/operands/template-validator/reconcile.go, internal/operands/template-validator/reconcile_test.go, main.go
Add a metric that increases when a common template is updated during
the reconcile step of the common_templates operand.
```release-note
Added metric named total_restored_common_templates that counts the number of common templates updated during reconcile.
```
=> Add total_restored_common_templates metrics

api/v1beta1/ssp_webhook.go, api/v1beta1/ssp_webhook_test.go, tests/commonTemplates_test.go, tests/webhook_test.go
Enable changing of namespace during run of ssp operator
/cc @akrejcir @rnetser 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1958085
```
Enable changing of namespace during run of ssp operator
```
=> Enable changing of namespace during run of ssp operator

Dockerfile, go.mod, validator.Dockerfile
The `golang-1.16` package is now available in `ubi8/ubi-minimal` image.
```release-note
Increased Golang version to 1.16
```
=> Increase golang version to 1.16

.github/workflows/release.yaml
change ACTIONS_TOKEN to secrets.GITHUB_TOKEN
with this change github actions will use one time token, which is
created and deleted during action run.
More info here: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
```
NONE
```
=> change ACTIONS_TOKEN to secrets.GITHUB_TOKEN

hack/csv-generator.go
`csv-generator` was doing string operations on YAML document, which could produce invalid YAML. This patch removes these operations.
This was the invalid transformation:
`'DataVolumeContentType options: "kubevirt", "archive"'` -> `'DataVolumeContentType options: "kubevirt", "archive"`
It removed the `'` at the end, making this an invalid string.
```release-note
None
```
=> Fix csv-generator's invalid YAML output

config/manager/manager.template.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/operands/template-validator/resources.go
The selector of the kubevirt servicemonitor changed,
as a result the metrics are not picked up by Prometheus,
and the Alert malfunction.
Changing the labels of ssp and operand pods accordingly.
```release-note
NONE
```
=> Fix Alerts firing, metrics missing bug

internal/operands/metrics/resources.go
We want to be able to list all kubevirt alerts so we added labels to differentiate them.
Signed-off-by: assafad aadmi@redhat.com
```release-note
Added common labels into alert definitions and constant to use as runbook url prefix
```
=> Add common labels into alert definitions 

config/rbac/role.yaml, controllers/crd_controller.go, controllers/finishable/finishable.go, controllers/setup.go, controllers/ssp_controller.go, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/common/scheme.go, internal/operands/common-templates/reconcile.go, internal/operands/data-sources/reconcile.go, internal/operands/metrics/reconcile.go, internal/operands/node-labeller/reconcile.go, internal/operands/operand.go, internal/operands/template-validator/reconcile.go, main.go
If not all needed CRDs are installed, a controller that watches and waits for CRDs will be started.
When CRDs are installed, the initial controller will exit and the SSP controller will start.
These CRDs are needed:
- `datavolumes.cdi.kubevirt.io`
- `datasources.cdi.kubevirt.io`
- `dataimportcrons.cdi.kubevirt.io`
- `prometheusrules.monitoring.coreos.com` (is installed with OCP)
Without this PR, the SSP controller would fail to watch the resources if their CRDs do not exist, and the application would exit with an error. Which would cause the operator deployment to enter a crash loop.
```release-note
The operator waits until all needed CRDs are installed.
```
=> Add initial controller to watch missing CRDs

internal/operands/common-templates/reconcile.go, internal/operands/metrics/resources.go
Alert changed to fire right away without pending.
Add a log line to know which template was reverted.
```release-note
SSPCommonTemplatesModificationReverted chnaged to fire without a delay.
Added log line "Changes reverted in common template: <template name>" to see which template was reverted.
```
=> Improve SSPCommonTemplatesModificationReverted Alert

internal/template-bundle/bundle.go, internal/template-bundle/bundle_test.go, internal/template-bundle/template-bundle-test.yaml
Parsing the VM template directly into `VirtualMachine` object may not always succeed, because the template can have parameters in places where the `VirtualMachine` definition does not allow strings.
This patch parses the template into `Unstructured` object.
```release-note
None
```
=> Parse VM from Template using Unstructured

controllers/ssp_controller.go
According to kubernetes API conventions the reason field of a Condition shall contain a CamelCased value.
This fixes the reason field of SSP status Conditions not following kubernetes API conventions
See https://bugzilla.redhat.com/show_bug.cgi?id=2032845
Fixes #
```release-note
The reason field of SSP status Conditions now follows kubernetes API conventions by using CamelCased values.
```
=> Use CamelCased reason values in SSP status Condition

internal/common/resource.go, internal/common/resource_test.go, internal/operands/common-templates/reconcile.go, internal/operands/data-sources/reconcile.go
Usually only the `.spec` field of resource is immutable, `.metadata` and `.status` can be updated.
With this PR, the resource is only deleted, if `.spec` is changed, otherwise it is updated.
Partially fixes bug: https://bugzilla.redhat.com/show_bug.cgi?id=2037290
```release-note
None
```
=> Delete immutable resources only if immutable part was changed

tests/dataSources_test.go
The bug in CDI that made them fail was fixed.
https://bugzilla.redhat.com/show_bug.cgi?id=2035008
```release-note
None
```
=> Re-enable DataImportCronTests

README.md
Node labeller is no longer provided by ssp-operator. It was moved to
kubevirt.
Update README.md to be correct.
```release-note
None
```
=> README.md: Remove node labeller functionality

api/v1beta1/ssp_types.go, controllers/setup.go, controllers/ssp_controller.go, internal/common/request.go, internal/common/resource.go, internal/operands/data-sources/reconcile.go, internal/operands/data-sources/reconcile_test.go, internal/template-bundle/bundle.go, internal/template-bundle/bundle_test.go, internal/template-bundle/template-bundle-test.yaml, internal/test-utils/test_utils.go, tests/dataSources_test.go
If a DataSource points to an existing PVC, it will be created and reconciled by the SSP operator.
If the PVC does not exist, the operator will instead create and reconcile DataImportCron,
This allows users to create their own golden image PVCs, and they will have higher priority
than auto updated images.
```release-note
DataImportCrons are only created for DataSources that do not point to an existing PVC.
```
=> Do not create DataImportCron if DataSource points to an existing PVC

internal/operands/data-sources/reconcile.go, tests/dataSources_test.go, tests/misc_test.go
Fixed a bug where label `cdi.kubevirt.io/dataImportCron` was not removed from `DataSource` when `DataImportCron` template is removed from SSP CR.
Fixed functional tests, when running with an existing SSP CR.
Fixes bug: https://bugzilla.redhat.com/show_bug.cgi?id=2044398
```release-note
None
```
=> Fix DataSource reconciliation when DataImportCron template is removed

Makefile, data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Updating the version, because `v0.13.0` was released.
```release-note
None
```
=> Change operator version to v0.14.0

internal/operands/data-sources/reconcile.go
When auto-update is enabled, CDI will set the app labels.
```release-note
None
```
=> DataSources: Set app labels only when auto-update is disabled

automation/e2e-functests/setup.sh, automation/e2e-upgrade-functests/run.sh, automation/e2e-upgrade-functests/setup.sh
They are no longer called by the CI
```release-note
None
```
=> Remove setup.sh scripts from automation folder

internal/operands/template-validator/reconcile.go, internal/operands/template-validator/reconcile_test.go, internal/operands/template-validator/resources.go, tests/validator_test.go
Default PodTemplateSpec now has a podAntiAffinity that makes pod replicas to be scheduled on different nodes.
This affinity will be merged with the requested one.
The merge affect nodeAffinity, podAffinity, podAntiaffinity, tolerations, and nodeSelector
Fixes #
```release-note
TemplateValidator has a podAntiAffinity that makes pod replicas to be scheduled on different nodes.
```
=> Add default podAntiAffinity to PodTemplateSpec

api/v1beta1/constants.go, internal/constants.go, internal/operands/data-sources/reconcile.go, internal/operands/data-sources/reconcile_test.go, tests/dataSources_test.go, vendor/kubevirt.io/ssp-operator/api/v1beta1/constants.go, webhooks/ssp_webhook.go, webhooks/ssp_webhook_test.go
The constant is changed when building a downstream image, but the change is not propagated to the `vendor` directory.
This patch moves the constant into `internal` package.
```release-note
None
```
=> Remove `GoldenImagesNSname` constant from `api` submodule

automation/e2e-upgrade-functests/run.sh, hack/validate-no-offensive-lang.sh
This PR adds a new parameter for `e2e-upgrade-functests` lane, which specifies the release branch with the latest release.
This is needed when a PR is targeted for a release branch that is not latest. Without this change, the CI would test downgrade, instead of upgrade.
```release-note
None
```
=> `e2e-upgrade-functests` lane tests release from a specified branch

automation/e2e-upgrade-functests/run.sh, automation/ocp-ci-run-e2e-upgrade-tests.sh, hack/validate-no-offensive-lang.sh
This patch adds a new parameter for `e2e-upgrade-functests lane`, which specifies the release branch with the latest release.
This is needed when a PR is targeted for a release branch that is not latest. Without this change, the CI would test
downgrade, instead of upgrade.
```release-note
None
```
=> [release-v0.13] `e2e-upgrade-functests` lane tests release from a specified branch

api/v1beta1/ssp_types.go, config/crd/bases/ssp.kubevirt.io_ssps.yaml, vendor/kubevirt.io/ssp-operator/api/v1beta1/ssp_types.go
When 'oc get ssp' command is executed,
that the '.status.phase' field will be displayed.
Fixes # https://github.com/kubevirt/ssp-operator/issues/322
```
Print column Phase when getting SSP objects by 'oc get ssp' command.
```
Signed-off-by: Ondrej Pokorny <opokorny@redhat.com>
=> Add new column

go.mod, go.sum
Reverting golang to `1.17`. The CI does not yet support go `1.18`.
```release-note
None
```
=> Revert golang version back to 1.17

.github/workflows/release.yaml, Makefile, hack/config.sh, tests/e2e-test-csv-generator.sh
Change docker commands into podman
```
Removes all docker references and replaces them with podman.
```
Signed-off-by: Ondrej Pokorny <opokorny@redhat.com>
=> Change docker commands into podman

Makefile, validator.Dockerfile
update validator dockerfile to use golang 1.18
```
NONE
```
=> update validator dockerfile to use golang 1.18

go.mod, go.sum, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go, vendor/modules.txt
bump prometheus/client_golang to v1.11.1
bump prometheus/client_golang to v1.11.1
```
NONE
```
=> [Backport release-v0.13]bump prometheus/client_golang to v1.11.1

data/common-templates-bundle/common-templates-v0.19.4.yaml
replaced SRC_PVC_NAME and SRC_PVC_NAMESPACE back to DATA_SOURCE_NAME and DATA_SOURCE_NAMESPACE
```
NONE
```
=> [backport release-v0.13] replace SRC_PVC_NAME and SRC_PVC_NAMESPACE 

tests/misc_test.go
update openshift.io/scc label test to check if scc label has value restricted-v2
```
NONE
```
=> update openshift.io/scc label test

controllers/ssp_controller.go, internal/controller/handler-hook/handler_hook.go
Logs the type and namespace/name of the object that triggered the reconciliation.
This change will be helpful for: https://bugzilla.redhat.com/2082912
```release-note
None
```
=> Log the reason why reconciliation is triggered

tests/misc_test.go
update rhel 9 container link
```
NONE
```
=> update rhel 9 container link

.github/workflows/pull-request.yaml, .github/workflows/release.yaml
Update github actions to use golang 1.18
```release-note
None
```
=> Update github actions to use golang 1.18

controllers/ssp_controller.go, internal/controller/predicates/predicates.go, internal/controller/predicates/predicates_test.go, internal/operands/common-templates/reconcile.go, internal/operands/data-sources/reconcile.go, internal/operands/metrics/reconcile.go, internal/operands/node-labeller/reconcile.go, internal/operands/operand.go, internal/operands/template-validator/reconcile.go, tests/cleanup_test.go, tests/monitoring_test.go, tests/tests_suite_test.go
Some changes in a resource are not relevant for the reoconcile function. Mainly changes in `.status` field.
This change adds a predicate to filter out these changes.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2082912
```release-note
None
```
=> Add predicates to only watch relevant resource changes

Dockerfile, controllers/ssp_controller.go, internal/controller/handler-hook/handler_hook.go, internal/controller/predicates/predicates.go, internal/controller/predicates/predicates_test.go, internal/operands/common-templates/reconcile.go, internal/operands/data-sources/reconcile.go, internal/operands/metrics/reconcile.go, internal/operands/node-labeller/reconcile.go, internal/operands/operand.go, internal/operands/template-validator/reconcile.go, tests/cleanup_test.go, validator.Dockerfile
Some changes in a resource are not relevant for the reconcile function. Mainly changes in `.status` field.
This change adds a predicate to filter out these changes.
This is a backport of 2 PRs:
- https://github.com/kubevirt/ssp-operator/pull/351
- https://github.com/kubevirt/ssp-operator/pull/361
```release-note
None
```
=> [release-v0.13] Add predicates to only watch relevant resource changes

tests/webhook_test.go
updated tests ID 5990 and ID 5989
these tests sometimes failed due to ssp cr conflict error.
This patch add retry logic, which tries to update CR multiple time if
error occures
```
NONE
```
=> Fix tests ID 5990 and ID 5989

tests/validator_test.go
add eventually in AfterEach in validator webhook tests which tries to delete template
```
NONE
```
=> add eventually in AfterEach in validator webhook tests which tries to delete template

Dockerfile, internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.5.yaml, validator.Dockerfile
change a way ho golang is installed in dockerfile
Because golang 1.16 is no longer available in ubi
image, all tests are failing. This commit downloads golang from official go site.
```
NONE
```
=> [backport release-v0.12] change a way ho golang is installed in dockerfile

automation/common/deploy-kubevirt-and-cdi.sh, automation/common/versions.sh
The CI in this release branch uses fixed versions of Kubevirt and CDI, because it may be incompatible with newest versions.
Kubevirt version: `v0.53.2`
CDI version: `v1.50.0`
```release-note
None
```
=> [release-v0.15] CI: Fix Kubevirt and CDI versions

tests/dataSources_test.go, tests/misc_test.go
This PR does two things:
1. Fix tests waiting for DVs to succeed in misc_test.go
CDI now garbage collects succeeded DVs by default, so relying on a DV
having status phase succeeded does not work anymore. When the importer
Pod of a PVC succeeded and the corresponding DV no longer exists it can
be treated as a successful import instead.
2. Disable CDI garbage collection for now in dataSources_test.go
CDI currently does not handle DataImportCrons properly when garbage
collecting DataVolumes, so as a temporary fix the garbage collection is
disabled via an annotation.
The following tests still fail:
- [[test_id:8112] should restore DataSource if DataImportCron removed from SSP …
=> Fix tests waiting for DVs to succeed

ci-builder/Dockerfile
The new go 1.19 ci image does not contain packages which ssp operator needs for tests. This commit adds new dockerfile, which installs all necessary packages needed for ssp operator
```
NONE
```
=> add dockerfile for ci builds

ci-builder/Dockerfile
add gettext package to ci builder dockerfile
this package is required due to command in makefile
```
NONE
```
=> add gettext package to ci builder dockerfile

config/rbac/role.yaml, controllers/setup.go, controllers/ssp_controller.go, internal/common/environment.go
SSP can't run on a plain kubernetes, because it requires the `Infrastructure` kind to be present on the cluster.
When deploying KubeVirt with HCO using OLM on plain kubernetes, the deployment is never completed because SSP operator never becomes ready. More details and full description of the issue can be found here: https://github.com/kubevirt/hyperconverged-cluster-operator/issues/2129
This PR disables the reconcilers and all the watches, when running in a plain K8s cluster, instead of killing the process.
That way, the SSP operator is runing and responding to the health and ready checks, but does nothing else. The result is that SSP is still not working on plain kubernetest, but the OLM deployment is successfully completed.
Fixes kubevirt/hyperconverged-cluster-operator#2129 …
=> Allow running the SSP Operator on plain kubernetes

tests/crypto_policy_test.go
Use the appropriate getter instead of hardcoding the deployment namespace to 'kubevirt'.
```release-note
None
```
=> crypto_policy_test.go: Do not hardcode SSP deployment NS

tests/crypto_policy_test.go, tests/env/env.go, tests/tests_suite_test.go
Introduce a getter for the SSP webhook service name and use it instead of hardcoding the name to 'ssp-webhook-service'.
```release-note
None
```
=> crypto_policy_test.go: Do not hardcode SSP webhook service name

tests/crypto_policy_test.go, tests/tests_suite_test.go
This is a manual backport of #454 due to a conflict in `tests/env/env.go`.
```release-note
None
```
=> [release-v0.16] crypto_policy_test.go: Do not hardcode SSP webhook service name

tests/crypto_policy_test.go
Decide at runtime whether to get the CA bundle of the webhook service certificate from service serving certificates or OLM.
Also prevent a naming collision with imports by renaming the httpClient.
```release-note
None
```
=> crypto_policy_test.go: Get CA bundle dynamically

tests/dataSources_test.go, tests/misc_test.go
This is a follow-up to https://github.com/kubevirt/ssp-operator/pull/418
1. Do not check PVC pod annotation because it might not be always present (i.e. when smartcloning).
2. Reenable CDI garbage collection in `dataSources_test.go`
3. Unquarantine no longer failing tests in `dataSources_test.go`
```release-note
None
```
=> Cleanup fixes for tests waiting for DVs to succeed

automation/common/versions.sh
- Fixed kubevirt to `v0.58.x`
- Fixed CDI to `v1.55.x`
```release-note
None
```
=> [release-v0.16] Fix major and minor versions of Kubevirt and CDI used in CI

.gitignore, Makefile, config/kubevirtci/kustomization.yaml, config/kubevirtci/manager-disable-webhooks.yaml, controllers/setup.go, docs/development.md, hack/kubevirt.sh, hack/kubevirtci.sh, hack/sync.sh
This change introduces support for deploying the SSP operator into a local kubevirtci deployed env, using the same 
implementation as the core kubevirt/kubevirt project.
Fixes #
```release-note
NONE
```
=> Introduce support for deployments via kubevirtci and kubevirt

internal/operands/common-instancetypes/reconcile.go, internal/operands/common-instancetypes/reconcile_test.go
This PR addresses a number of follow ups from #453 :
* `RequireCrds` are added for `VirtualMachineClusterInstancetype` and `VirtualMachineClusterPreference`
* The `ImmutableSpec` reconcile function is removed
* A `Cleanup` function is now provided that removes all cluster resources previously added by the operand 
Fixes #
Note that no functional coverage is introduced as we still use `4.11` in our jobs, functional coverage for these changes cannot be introduced until CI moves to `4.12`  and provides the above CRDs.
```release-note
NONE
```
=> Follow ups for common-instancetypes deployment

tests/metrics_test.go
Signed-off-by: João Vilaça <jvilaca@redhat.com>
This PR adds an e2e test to ensure the `total_restored_common_templates` metric is not incremented if a template is created/edited during and SSP operator upgrade
```release-note
Add e2e tests for total_restored_common_templates metric
```
=> Add e2e tests for total_restored_common_templates metric

data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml, data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
This is required as https://github.com/kubevirt/kubevirt/pull/8886 recently landed and blocks new instance types from being created with the `dedicatedCPUPlacement` attribute set.
https://github.com/kubevirt/common-instancetypes/releases/tag/v0.0.2-rc
Fixes #465
I've not had time to wrap this process in automation yet so this is a manual update. Hopefully automated by the next update.
```release-note
common-instancetypes has been updated to the v0.0.2-rc release.
```
=> common-instancetypes: Update to v0.0.2-rc

internal/operands/common-instancetypes/reconcile.go, internal/operands/common-instancetypes/reconcile_test.go
This change ensure the VirtualMachineCluster{Instancetype,Preference} CRDs are present before attempting to cleanup resources from the cluster. This is required as operators such as HCO remove dependent projects such as KubeVirt and the SSP operator in parallel thus cleanup must be resilient to the CRDs already being removed.
Fixes #466 
```release-note
NONE
```
=> common-instancetypes: Ensure CRDs are present before Cleanup

.gitignore, Makefile, hack/kubevirtci.sh
Avoiding the situation where make thinks there's nothing to do because the directory of the same name as the target exists:
```
$ make cluster-up
make: 'cluster-up' is up to date.
```
Fixes #
```release-note
NONE
```
=> kubevirtci: Move to _cluster-up

internal/operands/common-instancetypes/reconcile.go, tests/cleanup_test.go, tests/tests_suite_test.go
A quick follow up to https://github.com/kubevirt/ssp-operator/pull/467 to provide functional test coverage of the
behaviour through some existing but previously missed cleanup tests.
Fixes #
Draft until #467 lands.
```release-note
NONE
```
=> common-instancetypes: Add watched cluster CRDs to cleanup func test 

internal/operands/metrics/resources.go, tests/metrics_test.go
Signed-off-by: assafad <aadmi@redhat.com>
This PR adds to each of SSP alerts a label named `operator_health_impact`, which indicates how the alerts impact the operator health. This will enable us filtering alerts based on their impact on the operator health, and to later have an operator health metric, which will tell the user what is the aggregated operator health.
This label gets one of the following values:
- `critical` indicates that the alert fires due to an issue that impacts the operator's functionality badly, and an action must be taken immediately in order to solve it.
-  `warning` indicates that the alert fires due to an issue that soon might impact the operator's functionality badly, and the user should be warned in order to solve the …
=> Add `operator_health_impact` label to SSP alerts

tests/metrics_test.go
This avoids picking up old ReplicaSets when waiting for a version update by checking if the desired count of pods is greater than 0.
```release-note
None
```
=> metrics_test.go: Do not consider old ReplicaSets

controllers/setup.go
The operand itself deploys DataImportCrons defined by the SSP CR and DataSources based on the provided common-templates bundle. While the latter functionality should likely reside in the common-templates operand the DataImportCrons functionaility is useful in non-OpenShift environments alongside that of the common-instancetypes operand.
This change now ensures the data_sources operand runs on both OpenShift and non-OpenShift environments.
Fixes #
```release-note
The `data_sources` operand is now always deployed, regardless of the underlying environment being OpenShift or OKD.
```
=> data_sources: Always run the operand

Dockerfile, validator.Dockerfile
feat: update ssp and validator ubi containers to rhel9 in dockerfile
```
NONE
```
=> feat: update ssp and validator ubi containers to rhel9 in dockerfile

Dockerfile, validator.Dockerfile
feat: bump golang version in ssp and validator containers
this commit updates go version to latest available 1.19.5 in ssp and validator containers
```
NONE
```
=> feat: bump golang version in ssp and validator containers

data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
common-instancetypes: Update bundle to v0.0.3
https://github.com/kubevirt/common-instancetypes/releases/tag/v0.0.3
```release-note
Update common-instancetypes bundle to v0.0.3
```
=> Update common-instancetypes to v0.0.3

.github/workflows/release-vm-console-proxy.yaml
This will add release vm-console-proxy workflow. This workflow will be triggered by another release workflow in vm-console-proxy repository.
It should be merged before we merge https://github.com/kubevirt/vm-console-proxy/pull/2.
```release-note
None
```
=> ci: add release-vm-console-proxy workflow

controllers/reconciler.go, controllers/services_controller.go, controllers/setup.go, controllers/vm_controller.go, docs/development.md, internal/common/scheme.go, internal/operands/metrics/resources.go, main.go, tests/metrics_test.go, tests/monitoring_test.go
RHEL6 guests will be not supported on RHEL9 hosts anymore [1].
And CNV 4.13 is planned to be on RHCOS 9, so RHEL6 cannot be supported in CNV 4.13 anymore.
Adding a vm controller that watch for rhel 6 vms.
Rhel6 template adds a label in the vm in the format: `rhel6-<workload>-<flavor>`.
This label is checked to determine whether a vm is rhel6 or not.
[1] https://access.redhat.com/articles/973163#rhelkvm
Fixes #
```release-note
RHEL6 guests will be not supported on RHEL9 hosts anymore. Add alert for rhel6 running vms
```
/cc @akrejcir
=> Add alert for rhel6 running vms

data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml
common-instancetypes: Update bundle to v0.1.0
https://github.com/kubevirt/common-instancetypes/releases/tag/v0.1.0
```release-note
Update common-instancetypes bundle to v0.1.0
```
=> Update common-instancetypes to v0.1.0

automation/e2e-upgrade-functests/run.sh, internal/operands/vm-console-proxy/reconcile.go, internal/operands/vm-console-proxy/reconcile_test.go, tests/cleanup_test.go, tests/env/env.go, tests/tests_suite_test.go, tests/vm_console_proxy_test.go
This PR will add vm-console-proxy functional tests.
```release-note
Add vm-console-proxy functional tests
```
=> test: add vm-console-proxy functional tests

internal/operands/vm-console-proxy/reconcile_test.go, internal/test-utils/test_utils.go
Add and cleanup operand unit tests.
```release-note
Add and cleanup vm-console-proxy operand unit tests
```
=> test: add and cleanup vm-console-proxy operand

automation/common/deploy-kubevirt-and-cdi.sh
Enable `KubevirtSeccompProfile` feature gate, so VM can be started on OCP 4.13.
```release-note
None
```
=> fix: Update Kubevirt CR used in CI

tests/crypto_policy_test.go
The TLS policy tests cause the operator to enter crash loop. This commit adds code that waits until it is ready.
```release-note
None
```
=> fix: Wait for SSP operator to be ready after TLS policy tests

docs/development.md
Adds missing dev docs for `golangci-lint` and `pre-commit`.
Fixes #
```release-note
NONE
```
=> docs: Add golangci-lint and pre-commit dev docs

internal/operands/vm-console-proxy/reconcile.go, tests/tests_suite_test.go, tests/vm_console_proxy_test.go
This PR contains 2 changes to make functional tests less flaky:
Functions `RevertToOriginalSspCr()` now wait until SSP is deployed before returning.
This is useful, because reverting SSP may change TLS policy, which causes the pod to crash, and it may be some time before it is running again. If in the meantime, another test tries to update the SSP, it will fail, because the webhook cannot be reached.
When the annotation `ssp.kubevirt.io/vm-console-proxy-enabled` is removed from SSP CR, the operator waits for resources to be removed before setting the `status.phase` to `Deployed`.
```release-note
None
```
=> fix: console proxy and tests: Stabilize functional tests

internal/operands/template-validator/resources.go, internal/operands/vm-console-proxy/reconcile_test.go
Currently, if the registry is temporarily unavailable, the virt-template validator pod fails to launch, although the image was pulled onto the cluster earlier. By changing the ImagePullPolicy to IfNotPresent, the cluster won't try to pull again the image if the same image was pulled before.
Fixes #
https://issues.redhat.com/browse/CNV-26764
```release-note
Use ImagePullPolicy: IfNotPresent instead of Always
```
=> Use ImagePullPolicy: IfNotPresent instead of Always

tests/vm_console_proxy_test.go
This change fixes a race, where the tests did not wait until console proxy resources were deployed.
```release-note
None
```
=> fix: stabilize functests of VM Console proxy

tests/vm_console_proxy_test.go
add test id for vnc proxy
Fixes #
```release-note
None
```
=> Added test_id for vnc_console_proxy

internal/common/labels.go, internal/operands/vm-console-proxy/reconcile.go, internal/operands/vm-console-proxy/reconcile_test.go, internal/test-utils/test_utils.go
`Cleanup()` method of vm-console-proxy deletes resources from the correct namespace.
```release-note
None
```
=> fix: correctly delete proxy resources if namespace is not "kubevirt"

internal/operands/metrics/reconcile.go, internal/operands/metrics/reconcile_test.go, internal/operands/metrics/resources.go
When `RUNBOOK_URL_TEMPLATE` env variable is set, its value will be used as the runbooks URL template. Otherwise, keep using the default runbook URL template `https://kubevirt.io/monitoring/runbooks/%s`. 
This allows using different runbooks versions, in accordance with the installation.
Jira-ticket - https://issues.redhat.com/browse/CNV-14382
```release-note
None
```
=> Use `RUNBOOK_URL_TEMPLATE` env for the runbooks URL template

internal/common/labels.go, internal/operands/vm-console-proxy/reconcile.go
This is a backport of: https://github.com/kubevirt/ssp-operator/pull/538
`Cleanup()` method of vm-console-proxy deletes resources from the correct namespace.
```release-note
None
```
=> [release-v0.17] fix: correctly delete proxy resources if namespace is not "kubevirt"

controllers/setup.go, controllers/ssp_controller.go, internal/common/request.go, internal/crd-watch/crd-watch.go, internal/operands/common-instancetypes/reconcile.go, internal/operands/common-instancetypes/reconcile_test.go, internal/operands/common-templates/reconcile.go, internal/operands/data-sources/reconcile.go, internal/operands/metrics/reconcile.go, internal/operands/node-labeller/reconcile.go, internal/operands/operand.go, internal/operands/template-validator/reconcile.go, internal/operands/vm-console-proxy/reconcile.go
This PR does 2 changes:
- Create an interface for `CrdWatch` that can only be used to get missing CRDs.
- Remove `RequiredCrds()` method from operands. Needed CRDs are read from `WatchTypes`.
```release-note
None
```
=> refactor: Remove RequiredCrds() method from operands

internal/common/resource.go, internal/operands/common-instancetypes/reconcile.go, internal/operands/data-sources/reconcile.go, internal/operands/metrics/reconcile.go, internal/operands/node-labeller/reconcile.go, internal/operands/template-validator/reconcile.go, internal/operands/vm-console-proxy/reconcile.go
Added default update and status functions for most resources that are reconciled by the operator.
```release-note
None
```
=> refactor: add default update and status functions

automation/e2e-tekton/example-pipelines-test.sh
fix: wait for ssp operator in pipelines tests
pipelines tests have to wait until ssp deployment is fully deployed, before creating ssp CR.
Should unblock https://github.com/openshift/release/pull/39551
```
NONE
```
=> fix: wait for ssp operator in pipelines tests

.github/workflows/update-virtio-version.yaml
feat: migrate automation for bumping virtio version
migrate github automation for bumping virtio version from TTO to ssp operator.
```
NONE
```
=> feat: migrate automation for bumping virtio version

automation/e2e-tekton/example-pipelines-test.sh
fix: add validator image variable to pipeline test scripts
Add validator img link to example pipelines test script. Without this link, validator uses latest tag, which is 3 years old and ssp operator is in deploying phase, because validator is not working
```
NONE
```
=> fix: add validator image variable to pipeline test scripts

internal/operands/tekton-pipelines/tekton-pipelines.go, internal/operands/tekton-tasks/tekton-tasks.go, tests/tekton-pipelines_test.go, tests/tekton-tasks_test.go
Currently, we're watching to Tekton CRD which
means it's required CRD. This is not always the
case if the Feature Gate is disabled.
This is a quick workaround to the required
Tekton CRD even when Feature Gate is disabled.
A solution to that issue is tracked in #560.
```release-note
Do not watch Tekton CRD.
```
=> fix(CNV-29287): do not watch tekton crd

README.md, controllers/setup.go, controllers/vm_controller.go
fix: add virtualMachine.kubevirt.io crd to required crds
vm-controller is not checking if virtualMachine.kubevirt.io crd exists. this is causing troubles, when kubevirt crds are uninstalled when ssp oeprator
is running.
/hold
```
fix: add virtualMachine.kubevirt.io crd to required crds
```
=> fix: add virtualMachine.kubevirt.io crd to required crds

internal/common/labels.go, internal/operands/tekton-pipelines/tekton-pipelines.go, internal/operands/tekton-tasks/tekton-tasks.go
Checks if Tekton CRD is installed during Tekton
operands reconciliation and during cleanup
process when listing deprecated ClusterTasks.
```release-note
Ensure Tekton CRD exists during reconciliation and cleanup process.
```
=> fix(CNV-29761): ensure that tekton crd exists

.github/workflows/pull-request.yaml, hack/check-commited-changes.sh
This PR modifies the Makefile to execute script that checks whether all files are committed.
```
None
```
=> feat: Add checking that all files are committed

internal/common/resource.go, internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go, main.go, tests/metrics_test.go
SSPCommonTemplatesModificationReverted is being triggered during upgrades.
Fixes #
```release-note
Fix total_restored_common_templates metric update
```
=>  Fix total_restored_common_templates metric update

data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml, data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
common-instancetypes: Update bundle to v0.2.0
https://github.com/kubevirt/common-instancetypes/releases/tag/v0.2.0
Fixes #572
```release-note
Update common-instancetypes bundle to v0.2.0
```
=> Update common-instancetypes to v0.2.0

automation/common/versions.sh
The release `v0.17` depends on these specific versions.
```release-note
None
```
=> [release-v0.17] chore: Fix kubevirt and CDI versions in CI

data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml, data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
common-instancetypes: Update bundle to v0.3.0
https://github.com/kubevirt/common-instancetypes/releases/tag/v0.3.0
Fixes https://github.com/kubevirt/ssp-operator/issues/578
```release-note
Update common-instancetypes bundle to v0.3.0
```
=> Update common-instancetypes to v0.3.0

config/manager/manager.template.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml
fix: add VIRTIO_IMG env variable to manager manifest
remove VIRT_LAUNCHER env variable, which is not used anywhere.
VIRTIO_IMG is needed for tekton pipelines
PR to main will follow after this PR
/cc @akrejcir 
```
NONE
```
=> [release-v0.18] Fix env variables

internal/common/environment.go
Rename Tekton environment variables to be the
same as declared in CSV. Currently, they are not
the same as in CSV and no value is set.
```release-note
Fix Tekton images enviroment variables.
```
=> fix(CNV-30284): rename tekton images env vars

Makefile, hack/kubevirtci.sh, internal/operands/data-sources/reconcile.go, internal/operands/data-sources/reconcile_test.go
With CDI 1.57.0 we have a new [feature](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/os-image-poll-and-update.md#dataimportcron-source-formats) that introduces datasources that point to snapshot objects instead of PVCs.
We want to not override those, since this is the correct source to be pointing at.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2215285
```release-note
BugFix: SSP resets datasource reference to initial state
```
=> Don't override autoupdated datasources that point to a snapshot instead of PVC

data/tekton-pipelines/windows-bios-installer-pipeline.yaml, data/tekton-pipelines/windows-customize-pipeline.yaml, data/tekton-pipelines/windows-efi-installer-pipeline.yaml
fix: fix default instanceTypeName parameter in tekton pipelines
n1.large instance type was renamed to o1.large
```
fix default instanceTypeName parameter in tekton pipelines
```
=> fix: fix default instanceTypeName parameter in tekton pipelines

README.md
This PR adds a notification to the README that the development has been moved from the master branch to the main branch.
```
None
```
=> git rm -rf 

config/rbac/role.yaml, controllers/setup.go, controllers/ssp_controller.go, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/operands/common-instancetypes/reconcile.go, internal/operands/data-sources/reconcile.go, internal/operands/metrics/reconcile.go, internal/operands/tekton-pipelines/reconcile.go, internal/operands/tekton-tasks/reconcile.go, internal/operands/template-validator/reconcile.go, internal/operands/vm-console-proxy/reconcile.go
As it is now, some of the RBAC rules and/or verbs are not required for the operator to be able to perform all intended operations.
This PR audits all RBAC rules. The auditory has been carried out following a black box approach, i.e., remove all rules, deploy the operator, run functest, collect forbidden operations, add the missing rules/verbs and repeat. The auditing process has been split in the next action items:
- Deploying the operator in KubevirtCI.
- Deploying the operator in a CRC cluster and running the functest.
- Deploying the operator in a 3 masters and 3 workers nodes and running the functest.
- Deploying a custom downstream build and running the Tier 2 test.
Just in case changes are not clear enough, this is a simplified and normalized …
=> Audit RBAC rules

ci-builder/Dockerfile
Add Podman installation to `ci-builder/Dockerfile`, in order to be able to execute the metrics name linter within `make unittest`.
```release-note
None
```
=> Add Podman to ci-builder

.github/workflows/update-virtio-version.yaml
fix: GH actions for bumping virtio version
script contained wrong paths for files, which need update
```
NONE
```
=> fix: GH actions for bumping virtio version

data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml, data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
common-instancetypes: Update bundle to v0.3.1
https://github.com/kubevirt/common-instancetypes/releases/tag/v0.3.1
```release-note
Update common-instancetypes bundle to v0.3.1
```
=> Update common-instancetypes to v0.3.1

hack/prom_metric_linter.sh
Currently, the linter [PR](https://github.com/openshift/release/pull/41234) in CI is failing, since `make lint-metrics` gets to https://github.com/kubevirt/ssp-operator/blob/main/hack/config.sh#L8. This PR moves `source "${PROJECT_ROOT}"/hack/config.sh`, in the metrics linter script, so it will be executed only if the linter runs locally.
```release-note
None
```
=> Fix metrics linter script

api/v1beta2/ssp_types.go, config/crd/bases/ssp.kubevirt.io_ssps.yaml, config/samples/ssp_v1beta2_ssp.yaml, data/crd/ssp.kubevirt.io_ssps.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/operands/vm-console-proxy/reconcile.go, internal/operands/vm-console-proxy/reconcile_test.go, tests/tests_suite_test.go, tests/vm_console_proxy_test.go, vendor/kubevirt.io/ssp-operator/api/v1beta2/ssp_types.go
Add a new Feature Gate to deploy VM console
proxy resources.
Jira-Url: https://issues.redhat.com/browse/CNV-30283
Note: This PR is the cherry pick of #609 manually since automation didn't work because of conflicts.
```release-note
Add deployVmConsoleProxy feature gate
```
=> feat: add deploy VM console proxy feature gate

.github/workflows/add-reviewer-monitoring.yaml
This PR reworks the add reviewer workflow to simply add a '/cc user' comment and let Prow handle the rest.
```
None
```
=> feat: Rework add reviewer workflow

controllers/services_controller.go, tests/service_controller_test.go
Add required labels:
- "app.kubernetes.io/managed-by"
- "app.kubernetes.io/version"
- "app.kubernetes.io/component"
- "app.kubernetes.io/part-of"
That are required by a specific resource:
- ssp-operator-metrics
Jira-Url: https://issues.redhat.com/browse/CNV-28185
```release-note
Add required labels to SSP operator metrics
```
=> fix(CNV-28185): add required labels

tests/metrics_test.go
This PR adds a check to the alerts rules test, which verifies that the alerts `runbook_url` annotations has the alerts names as a suffix.
**Which issue(s) this PR fixes**: https://issues.redhat.com/browse/CNV-30798
```release-note
None
```
=> Force runbooks names to equal alerts names

automation/common/versions.sh
Version was pinned before Kubevirt `1.0.0` release. Now it can be unpinned.
```release-note
None
```
=> fix: CI uses the latest released Kubevirt

data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml, data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
common-instancetypes: Update bundle to v0.3.2
https://github.com/kubevirt/common-instancetypes/releases/tag/v0.3.2
```release-note
Update common-instancetypes bundle to v0.3.2
```
=> Update common-instancetypes to v0.3.2

controllers/ssp_controller.go, internal/common/crypto_policy.go, internal/template-validator/tlsinfo/tlsinfo.go, main.go, tests/crypto_policy_test.go
This PR adds the usage of callbacks to Prometheus and the webhook server, enabling the dynamic reloading of the TLS configuration. This eliminates the necessity of restarting the SSP pod, which had previously led to the pod entering the CrashLoopBackOff state.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2151248
```
None
```
=> fix: CrashLoopBackOff once tlsProfile changed

.github/workflows/release-vm-console-proxy.yaml, config/manager/manager.template.yaml, config/rbac/role.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, data/vm-console-proxy-bundle/vm-console-proxy.yaml, hack/csv-generator.go, hack/csv-generator_test.go, internal/common/environment.go, internal/operands/vm-console-proxy/defaults.go, internal/operands/vm-console-proxy/reconcile.go, internal/operands/vm-console-proxy/reconcile_test.go, internal/vm-console-proxy-bundle/bundle-test-duplicate.yaml, internal/vm-console-proxy-bundle/bundle-test-incorrect.yaml, internal/vm-console-proxy-bundle/bundle-test.yaml, internal/vm-console-proxy-bundle/bundle.go, internal/vm-console-proxy-bundle/bundle_test.go, tests/e2e-test-csv-generator.sh, tests/tests_suite_test.go, tests/vm_console_proxy_test.go
- Updated release script to change `vm-console-proxy` image tag.
- csv-generator uses `VM_CONSOLE_PROXY_IMAGE` environment variable to set the image.
```release-note
csv-generator can be used to set the image of vm-console-proxy.
```
=> fix: Use the latest image of vm-console-proxy

internal/operands/tekton-pipelines/reconcile.go, internal/operands/tekton-pipelines/reconcile_test.go
feat: replace namespace of configMaps and roleBindings
When ssp CR contains defined spec.tektonPipelines.namespace attribute, it should replace kubevirt.io/deploy-namespace annotation (currently used only for configMaps and roleBindings in example tekton pipelines). So when user decides to deploy pipelines to different namespace, the pipeline will be able to pick up correct configMap and roleBinding.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2229903
```
feat: replace namespace of configMaps and roleBindings in tekton pipelines
```
=> feat: replace namespace of configMaps and roleBindings

data/tekton-pipelines/windows-efi-installer-pipeline.yaml
fix: change delete object type in clean up section in efi pipeline
CDI changed behaviour of dataVolume garbage collector. It is now disabled by default. This is causing issue in finally section of efi pipeline, beause the pipeline is trying to delete PVCs, but because the fact, that datavolume is still present, the PVCs are not deleted.
This commit changes the PVC object kind to DataVolume in deleteObjectKind parameter. 
Revert PR for DV GC - https://github.com/kubevirt/containerized-data-importer/commit/0bc6a8aeca570ce138dd28616d15e8a06ce88c1e
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2227957
```
fix: change delete object type in clean up …
```
=> fix: change delete object type in clean up section in efi pipeline

.github/workflows/release-vm-console-proxy.yaml, config/manager/manager.template.yaml, config/rbac/role.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, data/vm-console-proxy-bundle/vm-console-proxy.yaml, hack/csv-generator.go, hack/csv-generator_test.go, internal/common/environment.go, internal/operands/vm-console-proxy/defaults.go, internal/operands/vm-console-proxy/reconcile.go, internal/operands/vm-console-proxy/reconcile_test.go, internal/vm-console-proxy-bundle/bundle-test-duplicate.yaml, internal/vm-console-proxy-bundle/bundle-test-incorrect.yaml, internal/vm-console-proxy-bundle/bundle-test.yaml, internal/vm-console-proxy-bundle/bundle.go, internal/vm-console-proxy-bundle/bundle_test.go, tests/e2e-test-csv-generator.sh, tests/tests_suite_test.go, tests/vm_console_proxy_test.go
This is a cherry-pick of: https://github.com/kubevirt/ssp-operator/pull/645
```release-note
csv-generator can be used to set the image of vm-console-proxy.
```
=> [release-v0.18] fix: Use the latest image of vm-console-proxy

automation/e2e-upgrade-functests/run.sh, config/samples/ssp_v1beta2_ssp.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, docs/configuration.md, internal/operands/vm-console-proxy/reconcile.go, internal/operands/vm-console-proxy/reconcile_test.go, tests/env/env.go, tests/tests_suite_test.go, tests/vm_console_proxy_test.go
Remove vm-console-proxy-namespace annotation that
is no longer relevant since a new released VM
console proxy is no longer require namespace
to operate, by default it was kubevirt as it
required an access to virt-handler (and also
virt-handler certificates).
Jira-Url: https://issues.redhat.com/browse/CNV-31248
```release-note
Remove vm-console-proxy-namespace annotation
```
=> refactor(CNV-31248): remove namespace annotation

automation/e2e-upgrade-functests/run.sh, config/samples/ssp_v1beta2_ssp.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/operands/vm-console-proxy/reconcile.go, internal/operands/vm-console-proxy/reconcile_test.go, tests/env/env.go, tests/tests_suite_test.go, tests/vm_console_proxy_test.go
This is a backport of: https://github.com/kubevirt/ssp-operator/pull/634
```release-note
Remove vm-console-proxy-namespace annotation
```
=> [release-v0.18] refactor(CNV-31248): remove namespace annotation

internal/template-validator/validation/path/path.go, internal/template-validator/validation/path/path_test.go, internal/template-validator/validation/test-utils/utils.go
fix: fix wrong parsing of vm.spec.template.spec.domain.memory.guest in validator
template validator could not parse pointer to resource.Quantity struct. This PR adds support for it
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2236545
```
NONE
```
=> fix: fix wrong parsing of vm.spec.template.spec.domain.memory.guest in validator

data/tekton-pipelines/pipelines-rbac.yaml, data/tekton-pipelines/windows-bios-installer-configmaps.yaml, data/tekton-pipelines/windows-customize-configmaps.yaml, internal/operands/tekton-pipelines/reconcile.go, internal/operands/tekton-pipelines/reconcile_test.go
fix: replacing of namespace annotation when kubevirt namespace is set
When ssp CR contains kubevirt namespace as a target namespace
for pipelines, ssp operator recognized this namespace as user defined
and deployed configmaps and roleBindings to a single namespace, instead
of two namespaces. That broke our default pipeline flow. This
change adds a check if the pipeline namespace in the CR is kubevirt,
then it is not used as a user defined namespace and
kubevirt.io/deploy-namespace annotation is used instead.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2237916
```
NONE
```
=> fix: replacing of namespace annotation when openshift-cnv namespace is set

internal/operands/metrics/resources.go, tests/monitoring_test.go
Instead of issuing one alert per VM, we now issue one alert, with the count of VMs with problems
Fixes #
```release-note
Reduce VirtualMachineCRCErrors noise
```
=> Reduce VirtualMachineCRCErrors noise

data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml, data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
common-instancetypes: Update bundle to v0.3.3
https://github.com/kubevirt/common-instancetypes/releases/tag/v0.3.3
```release-note
Update common-instancetypes bundle to v0.3.3
```
=> Update common-instancetypes to v0.3.3

data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml, data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
common-instancetypes: Update bundle to v0.3.4
https://github.com/kubevirt/common-instancetypes/releases/tag/v0.3.4
```release-note
Update common-instancetypes bundle to v0.3.4
```
=> Update common-instancetypes to v0.3.4

data/tekton-pipelines/windows-bios-installer-pipeline.yaml, data/tekton-pipelines/windows-customize-pipeline.yaml, data/tekton-pipelines/windows-efi-installer-pipeline.yaml
fix: remove "cdi.kubevirt.io/storage.bind.immediate.requested" annotation from pipelines
CDI does not honor this annotation when WFFC VolumeBindingMode is set. This is causing a problem, that PVCs are in pending state and pipelines fail.
this commit removes the annotations, because the pvcs are going to be consumed by VM.
Fixes https://github.com/kubevirt/containerized-data-importer/issues/2918
```
fix: remove "cdi.kubevirt.io/storage.bind.immediate.requested" annotation from pipelines
```
/hold WIP
=> fix: remove "cdi.kubevirt.io/storage.bind.immediate.requested" annotation from pipelines

config/rbac/role.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/operands/tekton-tasks/reconcile.go
It drops `*` verbs of tekton tasks. For this purpose, the process followed is:
* Drop all tekton tasks permissions using `*` verbs.
* Run unit tests.
* Add required permissions.
* Run functional tests.
* Add required permissions.
The auditing process has been split in the next action items:
* Deploying the operator in a CRC cluster and running the unit and function test.
* Deploying the operator in a 3 masters and 3 workers nodes and running the unit and functional tests.
This process ensures that only strictly required permissions are added. 
jira-ticket: [CNV-24031](https://issues.redhat.com/browse/CNV-24031)
Fixes # [https://bugzilla.redhat.com/show_bug.cgi?id=2223775](https://bugzilla.redhat.com/show_bug.cgi?id= …
=> rbac: Audit `*` verbs of kubevirt-tekton-tasks

internal/operands/common-instancetypes/reconcile.go, internal/operands/common-instancetypes/reconcile_test.go, tests/common_instancetypes_test.go
This PR introduces `IgnoreObjectOwnedByVirtOperator` to `reconcileBuilder` that as the name suggests ignores attempts to reconcile resources that are labelled as being owned by KubeVirt's `virt-operator`.
This is then used by the `common-instancetypes` operand ahead of deployment of these resources being enabled through `virt-operator` by https://github.com/kubevirt/kubevirt/pull/10309.
Future changes will also introduce a configurable to disable `common-instancetypes` deployment within SSP and ultimately deprecate the functionality ahead of removal in a future release of SSP.
Fixes #
```release-note
NONE
```
=> common-instancetypes: Ignore attempts to reconcile virt-operator owned objects from bundle

tests/common_instancetypes_test.go
fix: instance types tests by waiting for ssp to be deployed
```
NONE
```
=> fix: instance types tests by waiting for ssp to be deployed

data/crd/ssp.kubevirt.io_ssps.yaml
Regenerated CRD `data/crd/ssp.kubevirt.io_ssps.yaml` by running "make container-build"
```release-note
None
```
=> chore: Regenerate CRD in data folder

internal/operands/data-sources/reconcile.go, internal/operands/data-sources/reconcile_test.go
The `DataSource` reconciliation only reverted `PVC` field instead of whole `spec`.
```release-note
None
```
=> fix: Incorrect DataSource reconciliation

internal/common/resource.go, internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go
This is a manual cherry-pick of https://github.com/kubevirt/ssp-operator/pull/559
https://bugzilla.redhat.com/show_bug.cgi?id=2227787
Fixes #
```release-note
Fix total_restored_common_templates metric update
```
=> [release-v0.16] Fix total_restored_common_templates metric update

data/vm-console-proxy-bundle/vm-console-proxy.yaml, internal/operands/vm-console-proxy/reconcile.go
Use the latest patch version of `vm-console-proxy`.
```release-note
None
```
=> [release-v0.17] chore: Update version of vm-console-proxy container.

data/tekton-pipelines/windows-bios-installer-pipeline.yaml, data/tekton-pipelines/windows-customize-pipeline.yaml, data/tekton-pipelines/windows-efi-installer-pipeline.yaml
feat: add evictionStrategy to VMs in tekton pipelines
Sometimes when node crashes, VM is not migrated. This commit adds eviction strategy to VMs.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2221665
```
Add evictionStrategy to VMs in tekton pipelines
```
=> feat: add evictionStrategy to VMs in tekton pipelines

Makefile
This helps avoiding issues during CI runs, where vendoring fails after inadvertently changing the go.mod file.
Fixes #
```release-note
None
```
=> [release-v0.18] fix: Keep Ginkgo version in Makefile and go.mod in sync

.github/dependabot.yml
feat: introduce dependabot config
this PR introduces dependabot config for main and other release branches.
```
NONE
```
=> feat: introduce dependabot config

.github/workflows/pull-request.yaml, .github/workflows/release.yaml, ci-builder/Dockerfile
Updated `ci-builder` container and GitHub actions to use golang `1.20`.
This PR is a prerequisite for: https://github.com/kubevirt/ssp-operator/pull/745
Because the CI uses the `ci-builder` container from the current `HEAD`, not from the PR: https://docs.ci.openshift.org/docs/architecture/ci-operator/#build-root-image
```release-note
None
```
=> chore: Update golang in CI to 1.20

tests/webhook_test.go, webhooks/ssp_webhook.go, webhooks/ssp_webhook_test.go
The namespace of common templates is not checked in webhook.
Even if the webhook passes, user can still remove the namespace later.
Fixes: https://github.com/kubevirt/ssp-operator/issues/746
Fixes: https://issues.redhat.com/browse/CNV-35920
```release-note
Validation webhook does not check if namespace for templates exists.
```
=> fix: webhook: Don't check common template namespace

Makefile, internal/operands/common-instancetypes/reconcile_test.go, tests/dataSources_test.go, tests/tekton-pipelines_test.go, tests/tests_suite_test.go, tests/validator_test.go
Update golangci-lint to v1.55.2 and fix all issues the new versions uncovers.
Fixes #
```release-note
None
```
=> chore: Update golangci-lint to v1.55.2

tests/monitoring_test.go
Use the Route Status instead of the Route Spec to get the Prometheus host in monitoring tests. This avoids cases where the Route controller chose to expose the Route under a different Host than given in the Spec.
Fixes #
```release-note
None
```
=> fix: Use Route Status to get Prometheus host

automation/e2e-upgrade-functests/run.sh
Fix querying for the latest release of ssp-operator in e2e-upgrade-functests by increasing the number of branches per page to 100 (maximum).
Fixes #
This is only a temporary fix, the logic for getting branches needs to be extended to handle paginated results. See https://docs.github.com/en/rest/branches/branches?apiVersion=2022-11-28#list-branches--parameters
```release-note
None
```
=> fix: Fix querying for the latest release of ssp-operator

config/rbac/role.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/operands/tekton-tasks/tekton-tasks.go
This is a manual backport of https://github.com/kubevirt/ssp-operator/pull/684
```release-note
Replace `*`  tekton tasks verbs by individual verbs
```
=> [release-v0.18] rbac: Audit `*` verbs from kubevirt-tekton-tasks

controllers/vm_controller.go, docs/metrics.md, internal/operands/metrics/resources.go, pkg/monitoring/metrics/rbd_metrics.go, pkg/monitoring/metrics/rbd_metrics_test.go, tests/monitoring_test.go
The controller keeps reporting old metric values even after the VM is deleted. This PR updates the metric name and labels so that we can set up the metric value to 0, and no longer trigger the alert on VM deletion
Reduces VirtualMachineCRCErrors operator impact to none
Fixes #
```release-note
Fix VirtualMachineCRCErrors not stop firing
```
=> Fix VirtualMachineCRCErrors not stop firing

internal/common/labels.go, internal/operands/template-validator/reconcile.go, internal/operands/vm-console-proxy/reconcile.go
Add required labels (managed-by, part-of, version, component) to template-validator and vm-console-proxy pods.
Jira-Url: https://issues.redhat.com/browse/CNV-28185
```release-note
Add required labels to template-validator and vm-console-proxy pods.
```
=> fix: add required labels to pods

.github/dependabot.yml
this PR removes configuration for release branches,
because it created a lot of PRs with indirect dependencies.
It allows grouping of updates into single PRs
```
NONE
```
=> feat: dependabot configuration

.github/dependabot.yml
feat: set special labels to dependabot PRs
Set release-note-none and ok-to-test labels to
prs which were created by dependabot
```
NONE
```
=> feat: set special labels to dependabot PRs

data/tekton-pipelines/windows-efi-installer-configmaps.yaml
fix: increase partition1 size in windows efi configmaps
The windows11-autounattend configMap set the partition1 to 300MB, which is the minimum according to documentation. In practice, however, this causes the installer to create an extra partition at the end of the C: partition, blocking it from expanding. Then during windows update the disk fills up. This commit updates it to 700MB.
Fixes https://issues.redhat.com/browse/CNV-36289
```
fix: increase partition1 size in windows efi configmaps
```
=> fix: increase partition1 size in windows efi configmaps

controllers/vm_controller.go
Sometimes some resources might not exist yet and we see a huge amount of logs stating that an error created the VM metrics.
This PR:
- adds 5 seconds backoff between failed reconcile loops of VM controller to reduce the number of logs 
- removes 'error' wording from logs when the VM controller does not create the VM-related metrics, since it might not represent more serious problems, and might deceive users
- skips metric creation when VM-related resources are still in Provisioning status
jira-ticket: https://issues.redhat.com/browse/CNV-35806
```release-note
Update VM controller error handling
```
=> Update VM controller error handling

Makefile, hack/metrics-rules-test.sh, internal/operands/metrics/resources.go, pkg/monitoring/rules/rules-tests.yaml, pkg/monitoring/rules/rules.go, tests/monitoring_test.go, tools/metricsdocs/metricsdocs.go, tools/prom-metrics-collector/metrics_collector.go, tools/test-rules-writer/test_rules_writer.go
Added unit tests for prometheus metrics alerts.
Fixes: https://issues.redhat.com/browse/CNV-29476
```release-note
None
```
=> feat: Metrics unit tests

data/tekton-pipelines/windows-bios-installer-pipeline.yaml, data/tekton-pipelines/windows-efi-installer-pipeline.yaml
fix: set boot source labels for DVs created by windows pipelines
Set default instanceType and preferences labels to result DVs created by windows pipelines. With this fix, preferences will have default windows boot source when user triggers pipeline.
Fixes https://issues.redhat.com/browse/CNV-34661
```
fix: set boot source labels for DVs created by windows pipelines
```
=> fix: set boot source labels for DVs created by windows pipelines

tests/monitoring_test.go
Getting the token using TokenRequest API is more stable than listing all secrets and looking for the right one.
Cherry-pick of https://github.com/kubevirt/ssp-operator/pull/858
```release-note
None
```
=> [release-v0.18] fix: Use TokenRequest API to get prometheus token

config/rbac/role.yaml, controllers/controllers_suite_test.go, controllers/reconciler.go, controllers/setup.go, controllers/webhook_controller.go, controllers/wehook_test.go, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, tests/webhook_controller_test.go
The `ValidatingWebhookConfiguration` created by OLM can have `namespaceSelector` field set. We don't want it, because the webhook checks that there is only one SSP resource in the cluster.
Jira: https://issues.redhat.com/browse/CNV-36636
```release-note
None
```
=> fix: Remove namespaceSelector from webhook definition

tests/monitoring_test.go
Related issue: https://github.com/kubevirt/ssp-operator/issues/889
```release-note
None
```
=> test: Disable flaky test: [test_id:10549] Should fire VMStorageClassWarning when rxbounce is disabled

internal/template-validator/validation/test-utils/utils.go
`kubevirt.io/v1alpha3` is now deprecated in favour of `kubevirt.io/v1`.
Related to but not a fix for #716
```release-note
NONE
```
=> fix: Remove use of kubevirt.io/v1alpha3 in template-validator tests

Makefile
The version in `Makefile` was not updated by dependabot.
```release-note
None
```
=> chore: Update Ginkgo version in Makefile

data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml, data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
While we wait for automation to be fixed by https://github.com/kubevirt/common-instancetypes/issues/162 this is a manual sync of the older v0.3.5 release to the stable release-v0.18 branch of SSP.
Fixes #
```release-note
Updated common-instancetypes bundles to v0.3.5
```
=> [release-v0.18] chore: Update of common-instancetypes bundles to v0.3.5

hack/bump-common-instancetypes.sh
This change copies logic previously held in the `periodic-update-common-instancetypes-bundles` job into the SSP repo. This will allow us to remove the duplicate logic from the job definition in the future, simplifying it greatly.
Partial Fix# https://github.com/kubevirt/common-instancetypes/issues/162
```release-note
NONE
```
=> chore: Add script to sync common-instancetypes

controllers/vm_controller.go, docs/metrics.md, internal/operands/metrics/resources.go, pkg/monitoring/metrics/rbd_metrics.go, pkg/monitoring/metrics/rbd_metrics_test.go, tests/monitoring_test.go
This is a manual cherry-pick of https://github.com/kubevirt/ssp-operator/pull/742
https://issues.redhat.com/browse/CNV-35848
```release-note
Fix VirtualMachineCRCErrors not stop firing
```
=> [release-v0.18] Fix VirtualMachineCRCErrors not stop firing

config/rbac/role.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, data/vm-console-proxy-bundle/vm-console-proxy.yaml, internal/operands/vm-console-proxy/defaults.go, internal/operands/vm-console-proxy/reconcile.go, internal/operands/vm-console-proxy/reconcile_test.go, internal/vm-console-proxy-bundle/bundle-test.yaml, internal/vm-console-proxy-bundle/bundle.go, internal/vm-console-proxy-bundle/bundle_test.go
Updated `vm-console-proxy` to version `v0.5.0`, and changed code to support multiple `ClusterRoles`.
```release-note
Updated vm-console-proxy to version v0.5.0.
```
=> chore: Update vm-console-proxy to v0.5.0

data/tekton-pipelines/windows-bios-installer-pipeline.yaml, data/tekton-pipelines/windows-efi-installer-pipeline.yaml, internal/common/environment.go
Update virtio image version to v1.2.0
```release-note
chore: Update virtio image version to v1.2.0
```
=> chore: Update virtio image version to v1.2.0

Makefile, go.mod, go.sum, pkg/monitoring/rules/rules.go, pkg/monitoring/rules/rules_test.go, vendor/github.com/grafana/regexp/.gitignore, vendor/github.com/grafana/regexp/LICENSE, vendor/github.com/grafana/regexp/README.md, vendor/github.com/grafana/regexp/backtrack.go, vendor/github.com/grafana/regexp/exec.go, vendor/github.com/grafana/regexp/onepass.go, vendor/github.com/grafana/regexp/regexp.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_custom_validations.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_validation.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/linter.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/problem.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/recording_rule_validation.go, vendor/modules.txt
Apply the following linters:
- [monitoringlinter](https://github.com/kubevirt/monitoring/tree/main/monitoringlinter) that was implemented in https://github.com/kubevirt/monitoring/pull/221, and was designed to enforce https://github.com/kubevirt/community/pull/219.
This linter ensures that all monitoring-related practices are implemented within the `pkg/monitoring` directory using [operator-observability](https://github.com/machadovilaca/operator-observability/tree/main) methods. It verifies that all metrics, alerts and recording rules registrations are centralized in this directory, and restricts the direct use of [Prometheus registration methods](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#Registerer).
Example for a message …
=> Apply monitoring linters

hack/bump-common-instancetypes.sh
/cc @0xFelix 
The releases/latest GitHub API doesn't include pre-releases however we'd like to sync these to the main branch of kubevirt/ssp-operator for testing ahead of GA.
Fixes #
```release-note
NONE
```
=> bump-common-instancetypes.sh: Allow RC releases to be sync'd

automation/common/versions.sh
The SSP version in this branch should work with kubevirt `v1.1.x` and CDI `v1.58.x`.
```release-note
None
```
=> [release-v0.19] CI: Fix kubevirt and CDI versions for this branch

automation/common/versions.sh
The SSP version in this branch should work with kubevirt `v1.0.x` and CDI `v1.57.x`.
```release-note
None
```
=> [release-v0.18] CI: Fix kubevirt and CDI versions for this branch

config/manager/manager.template.yaml, config/samples/ssp_v1beta2_ssp.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, hack/csv-generator.go, hack/csv-generator_test.go, internal/common/environment.go, internal/common/environment_test.go, internal/common/labels.go, internal/common/resource.go, tests/tests_suite_test.go
This removes minor usages of tekton from these places:
- CSV generator
- Environment variables used by operator
- SSP CR example
- Default update function for reconcile code
- SSP CR created by functional tests
Removes unused `virtioImage` code.
```release-note
None
```
=> cleanup: Remove unused tekton and virtioImage code

README.md, docs/configuration.md, docs/development.md, docs/installation.md
Removed invalid sections in documentation:
- Parts related to tekton.
- Mention of VM proxy annotation.
```release-note
Removed invalid sections from documentation.
```
=> docs: Remove invalid documentation

controllers/ssp_controller.go, internal/common/request.go, internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go
The metric `kubevirt_ssp_common_templates_restored_total` should be increased if user changes a template and the operator restores it back to what it should be.
If the SSP CR is changed, for example one of the labels that are propagated to the templates are changed, then the reconciliation should not increase the metric.
Fixes: https://issues.redhat.com/browse/CNV-39928
```release-note
None
```
=> fix: Increase reconcile metric only if SSP CR was not changed

controllers/ssp_controller.go, internal/common/request.go, internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go
Manual cherry-pick of: https://github.com/kubevirt/ssp-operator/pull/950
It was needed, because metrics code was refactored in `main`.
The metric "kubevirt_ssp_common_templates_restored_total" should be increased if user changes a template and the operator restores it back to what it should be.
If the SSP CR is changed, for example one of the labels that are propagated to the templates are changed,
then the reconciliation should not increase the metric.
Fixes: https://issues.redhat.com/browse/CNV-39928
```release-note
None
```
=> [release-v0.19] fix: Increase reconcile metric only if SSP CR was not changed

docs/metrics.md, pkg/monitoring/rules/recordingrules/vmi.go
With https://github.com/kubevirt/kubevirt/pull/11283 we added guest OS labels to `kubevirt_vmi_phase_count` metric.
Now, we are able to use those labels in `cnv:vmi_status_running:count` recording rule.
Fixes https://issues.redhat.com/browse/CNV-37369 and required by https://issues.redhat.com/browse/CNV-38482.
```release-note
Add guest OS labels to cnv:vmi_status_running:count recording rule
```
=> Add guest OS labels to cnv:vmi_status_running:count

controllers/services_controller.go
The service that exposes metrics used to force IPv4 protocol. It failed in clusters that have only IPv6.
Fixes: https://issues.redhat.com/browse/CNV-40159
```release-note
None
```
=> fix: Do not force IPv4 on metrics service

config/rbac/role.yaml, controllers/controllers_suite_test.go, controllers/reconciler.go, controllers/setup.go, controllers/webhook_controller.go, controllers/wehook_test.go, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, tests/webhook_controller_test.go
This is a backport of: https://github.com/kubevirt/ssp-operator/pull/879
The `ValidatingWebhookConfiguration` created by OLM can have `namespaceSelector` field set. We don't want it, because the webhook checks that there is only one SSP resource in the cluster.
Jira: https://issues.redhat.com/browse/CNV-36636
```release-note
None
```
=> [release-v0.19] fix: Remove namespaceSelector from webhook definition

controllers/controllers_suite_test.go, controllers/reconciler.go, controllers/setup.go, controllers/webhook_controller.go, controllers/wehook_test.go, tests/webhook_controller_test.go
This is a backport of: https://github.com/kubevirt/ssp-operator/pull/879
The `ValidatingWebhookConfiguration` created by OLM can have `namespaceSelector` field set. We don't want it, because the webhook checks that there is only one SSP resource in the cluster.
Jira: https://issues.redhat.com/browse/CNV-36636
```release-note
None
```
=> [release-v0.18] fix: Remove namespaceSelector from webhook definition

pkg/monitoring/rules/alerts/operator.go, pkg/monitoring/rules/rules-tests.yaml
VMStorageClassWarning is being fired for VMs of all OSs, but although technically possible, the error never happened or was reproduced in non-Windows VMs. This PR updates the alert to fire only for Windows VMs.
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-38482
```release-note
Alert VMStorageClassWarning only for Windows VMs
```
=> Alert VMStorageClassWarning only for Windows VMs

internal/constants.go, internal/env/env.go, internal/env/env_test.go
These constants are edited in the downstream `Dockerfile`. Having them in a single file is more convenient.
Currently downstream builds from `main` branch fail, because the constant `defaultOperatorVersion` was moved in a previous PR: https://github.com/kubevirt/ssp-operator/pull/987
```release-note
None
```
=> chore: Move downstream edited constants to a single file.

Makefile
Prometheus was downloaded only for amd64. The make unittest
calls the tool under the hood. This fix enables the download for
another architectures.
Signed-off-by: Nestor Acuna Blanco <Nestor.Acuna@ibm.com>
**What type of PR is this?**
/kind bug
**What this PR does / why we need it:**
**Which issue(s) this PR fixes:**
Fixes #
**Special notes for your reviewer:**
**Does this PR introduce a user-facing change?:**
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**
=> fix: enable make unittest for different architectures.

automation/common/deploy-kubevirt-and-cdi.sh
Just a simple typo I found while reading the script
Fixes #
```release-note NONE
```
=> fix: typo in deploy-kubevirt-and-cdi.sh

tests/metrics_test.go
Fix runbook_url test to not expect the alert name as the URL suffix, as in some installations the alert name is not the URL suffix.
e.g. in openshift the runbooks are in https://github.com/openshift/runbooks/tree/master/alerts/openshift-virtualization-operator, and the suffix is `<alert-name>.md`.
```release-note
None
```
=> Fix runbook_url test

ci-builder/Dockerfile
Updated the CI builder to use golang 1.22.5.
This has to be done before any PR that needs it: https://github.com/kubevirt/ssp-operator/pull/1008
```release-note
None
```
=> deps: Update ci-builder to go 1.22.5

ci-builder/Dockerfile
Downstream uses golang `1.22.4`.
```release-note
None
```
=> ci-builder: Lower go version to downstream version

automation/common/versions.sh
The newer tekton versions changed CRD names, and so the operator cannot find objects from a given CRD.
```release-note
None
```
=> CI: Use compatible tekton version v0.67

automation/common/versions.sh
Kubevirt, CDI and Tekton are fixed to compatible versions.
```release-note
None
```
=> [release-v0.20] CI: Fix Kubevirt, CDI and Tekton versions

automation/common/versions.sh
The newer tekton versions changed CRD names, and so the operator cannot find objects from a given CRD.
```release-note
None
```
=> [release-v0.18] CI: Use compatible tekton version v0.67

automation/common/versions.sh
The newer tekton versions changed CRD names, and so the operator cannot find objects from a given CRD.
```release-note
None
```
=> [release-v0.19] CI: Use compatible tekton version v0.67

internal/operands/common-instancetypes/reconcile.go, internal/operands/common-instancetypes/reconcile_test.go
Previously, this order of operations would trigger a bug:
- set `.spec.commonInstancetypes.url` to a URL - The operator will deploy resources from the URL
- unset `.spec.commonInstancetypes.url` - The operator will deploy resources from internal bundle
- set `.spec.commonInstancetypes.url` to the same URL - The operator will ignore the resources and not deploy anything
```release-note
None
```
=> fix: common-instancetypes: Clear URL when deploying from bundle

tests/dataSources_test.go, tests/tests_suite_test.go
When running functional tests in an existing SSP deployment, the `DataImportCrons` are removed and recreated multiple times. The PVCs that they point to can be removed in the process.
One of the tests was removing the namespace that contains `DataImportCrons` and imported images. This caused a problem when the same namespace also contained `ImageStreams` for the imported images.
This PR adds code in `AfterSuite()` to wait for the PVCs to be imported again, and removes the test case, because it is already covered in unit tests.
```release-note
None
```
=> tests: On cleanup, wait until PVCs are bound.

tests/dataSources_test.go, tests/tests_suite_test.go
Reverts kubevirt/ssp-operator#1076
The PR does not solve the issue. Before the PR, the problem was a race, now it is happening always, deterministically.
These are the steps that cause downstream tests to fail:
- HCO deploys SSP, and then it creates `ImageStreames` in the golden images namespace.
- Test script scales HCO operator down to 0.
- SSP functional tests are run.
- One of the tests checks that all owned resources are removed when SSP object is removed. The golden image namespace is owned by SSP, so it is removed.
- The `ImageStreames` are also removed, but they are not recreated, because HCO operator is not running.
- The `AfterEach()` fails, because the `DataImportCrons` are waiting for the `ImageStreames` that will not be created.
Reverting this PR removes the wait in …
=> Revert "tests: On cleanup, wait until PVCs are bound."

Dockerfile
Git was used by kustomize, that was used to read instance types from a URL. Recently instance types and preferences were removed from SSP.
Jira: https://issues.redhat.com/browse/CNV-44449
```release-note
None
```
=> feat: Remove unused git from Dockerfile

Dockerfile, Makefile, validator.Dockerfile
This update adapts the Makefile and the Dockerfiles (ssp and validator) to enable automatic building on both s390x and amd64 architectures using make commands.
Fixes #
```release-note NONE
```
=> s390x enablement. Update Makefile and Dockerfiles

Dockerfile, validator.Dockerfile
**What this PR does / why we need it**: better readability
Fixes #
```release-note
NONE
```
=> refactor: suggestions from sonarcloud quality gate

tests/monitoring_test.go, tests/tests_common_test.go
Fix flaky test: [test_id:10549] Should fire VMStorageClassWarning when rxbounce is disabled
jira-ticket: https://issues.redhat.com/browse/CNV-47434
Fixes #
```release-note
NONE
```
=> Fix flaky test fire VMStorageClassWarning when rxbounce is disabled

Makefile
Use the same ginkgo version in `Makefile` that is in `go.mod`.
```release-note
None
```
=> makefile: use the same ginkgo version that is in go.mod

.github/dependabot.yml
Updated dependabot config to allow updating ginkgo.
The ignore config did not work.
Makefile was changed to read ginkgo version from go.mod
```release-note
None
```
=> chore: Allow dependabot to update ginkgo

tests/cleanup_test.go
Previously the error message contained the whole object, but the text was too long and it was truncated, so often we could not read the name and namespace of the objects.
Now we show only group, version, kind, namespace and name.
```release-note
None
```
=> tests: Show clearer error message when cleanup tests fail

Makefile
This enhancement reduces debugging time when executing the function tests.
Fixes #
```release-note
NONE
```
=> feat: filter function tests with GINKGO_FOCUS environment variable

internal/common/crypto_policy.go, internal/operands/template-validator/reconcile.go, internal/operands/template-validator/reconcile_test.go, internal/operands/template-validator/resources.go, internal/template-validator/filewatch/filewatch.go, internal/template-validator/filewatch/filewatch_test.go, internal/template-validator/tlsinfo/tlsinfo.go, internal/template-validator/tlsinfo/tlsinfo_test.go, internal/template-validator/validator/app.go, tests/crypto_policy_test.go, tests/validator_test.go
This PR moves the TLS configuration of `template-validator` to a ConfigMap. It is mounded as a file in the pod, and validator is able to update its configuration without restarting the pod.
Jira: https://issues.redhat.com/browse/CNV-28716
```release-note
None
```
=> feat: validator: Load TLS configuration from ConfigMap

tests/tests_suite_test.go, tests/validator_test.go
Fixes #
```release-note
NONE
```
=> test: enable end-to-end validator tests on s390x.

internal/template-bundle/bundle.go, internal/template-bundle/bundle_test.go, internal/template-bundle/template-bundle-test.yaml, tests/commonTemplates_test.go, tests/tests_suite_test.go
This change requires templates to define their architecture.
Fixes #
```release-note
NONE
```
=> feat: architecture dependent template reading

internal/controllers/setup.go, internal/template-bundle/bundle.go, internal/template-bundle/bundle_test.go
This change prepares for architecture-specific delivery. The logic will first attempt to locate the architecture-specific common templates bundle. If it is not found, it will then fall back to the generic bundle.
Fixes #
```release-note
NONE
```
=> feat: read architecture specific common templates file

Makefile
On older versions of podman, the command requires 2 arguments. We need it for the release workflow that runs Ubuntu 22.04 with podman v3.4.4.
Because of this issue, uploading release manifests to Quay failed for `v0.22.0` release.
```release-note
None
```
=> makefile: Fix podman manifest push command

tests/monitoring_test.go
The test scales SSP deployment down and then scales it back up. It was probably failing because one minute was not enough time to become ready.
```release-note
None
```
=> tests: Increase timeout waiting for SSP deployment to be ready.

Dockerfile, api/go.mod, ci-builder/Dockerfile, go.mod, validator.Dockerfile, vendor/modules.txt
Downstream build now supports golang version 1.23.2.
This PR will unblock dependabot's PRs for automatic updates.
```release-note
None
```
=> feat: Update golang version to 1.23.2

config/rbac/role.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, go.mod, internal/common/labels.go, internal/controllers/setup.go, internal/operands/vm-delete-protection/reconcile.go, internal/operands/vm-delete-protection/reconcile_test.go, internal/operands/vm-delete-protection/resources.go, tests/cleanup_test.go, tests/vm_delete_protection_test.go
VirtualMachine objects are often managed by automation, CLI commands, 3rd party tools, etc. These automations may result in deleting accidentally VMs that should have not been deleted. These deletions may lead to a service degradation or out of service. Moreover, the deleted VMs may lead to information loss if the underlining PVC is deleted as a result of a cascaded delete.
It adds the ability to protect VirtualMachine objects from being deleted. If the label `kubevirt.io/vm-delete-protection` is set to `True`, any attempt to delete the VM will be rejected by a VAP policy.
This protection enables a protection against non-intended VM deletions, providing security and confidence to users.
Fixes # …
=> feat: Add VM delete protection

.github/dependabot.yml
Add dependabot configuration for api. It will weekly update api dependencies.
```release-note
None
```
=> Add dependabot configuration for api

README.md, docs/development.md
Highlights what it is the new operand, how to use the feature and where the VAP can be located.
Fixes # [CNV-50737](https://issues.redhat.com/browse/CNV-50737)
```release-note
None
```
=> docs: Add vm-delete-protection operand

Makefile, config/crd/bases/ssp.kubevirt.io_ssps.yaml, config/rbac/role.yaml, data/crd/ssp.kubevirt.io_ssps.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml
It will help to unlock further updates in SSP. Currently, the controller-gen tool fails with latest external deps updates.
This should unlock dep updates such as https://github.com/kubevirt/ssp-operator/pull/1221
```release-note
None
```
=> deps: Updates controller-tools version

internal/template-bundle/bundle.go
This update explains why the check of the teamplateArch is still needed. It maintains compatibility in case changes for other architectures are delivered solely through the generic common templates.
```release-note
NONE
```
=> doc: Update disclaimer in readTemplates

README.md
=> doc: common instancetypes are not released to the SSP

api/go.mod, api/go.sum, api/vendor/modules.txt, go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/priorityqueue/metrics.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/priorityqueue/priorityqueue.go, vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
Bumps the production-dependencies group in /api and / with 1 update: [sigs.k8s.io/controller-runtime](https://github.com/kubernetes-sigs/controller-runtime).
Updates `sigs.k8s.io/controller-runtime` from 0.20.0 to 0.20.1
- [Release notes](https://github.com/kubernetes-sigs/controller-runtime/releases)
- [Changelog](https://github.com/kubernetes-sigs/controller-runtime/blob/main/RELEASE.md)
- [Commits](https://github.com/kubernetes-sigs/controller-runtime/compare/v0.20.0...v0.20.1)
---
updated-dependencies:
- dependency-name: sigs.k8s.io/controller-runtime dependency-type: direct:production update-type: version-update:semver-patch dependency-group: production-dependencies ...
Manual update of dependabot PR: …
=> chore(deps): Bump sigs.k8s.io/controller-runtime

.github/workflows/create-release-branch.yaml, .github/workflows/release.yaml
- Added github workflow to create a new release branch and a PR to activate CI for the new branch
- Improve the release workflow to add API tag when release is created.
Fixes: https://github.com/kubevirt/ssp-operator/issues/585
Jira: https://issues.redhat.com/browse/CNV-47126
```release-note
None
```
=> chore: Improve release automation

automation/common/versions.sh
Fixes kubevirt and CDI versions for this release branch.
```release-note
None
```
=> [release-v0.22] CI: Fix kubevirt and CDI versions

hack/check-commited-changes.sh
It improves the output of script check_commite_changes by showing which files have not been commited in the PR. It should help developers to locate the issue in the PR.
```release-note
None
```
=> chore(CI): Improve uncommited files vebosity

tests/vm_delete_protection_test.go
There is a race condition between the deletion in those test in which the deletion is expected to happen and the `AfterEach` `IsNotFound` check. This may cause that the `AfterEach` tries to update the VM to remove the label, but the VM is already gone.
It adds a `WaitForDeletion` in those test to be sure that the VM is removed before triggering the `AfterEach`. Moreover, it adds a check in the `AfterEach` to check if the VM is already being deleted.
Fixes # https://github.com/kubevirt/ssp-operator/issues/1239
```release-note
None.
```
=> chore(test): Add cleanup in VM delete protection test

renovate.json
fix: regex in renovate config
previous regex caused Renovate to evaluate branches created by renovate as matching. To fix this, the ^ and $ are added to the regex.
```
NONE
```
=> fix: regex in renovate config

tests/commonTemplates_test.go, tests/metrics_test.go, tests/metrics_test_utils.go, tests/misc_test.go, tests/port-forwarding.go, tests/tests_common_test.go, tests/validator_test.go
Sometimes the port-forwarding in metrics tests would fail, but we didn't get a reasonable error message.
This PR improve the error messages, so failures are easier to debug.
Fixes: https://issues.redhat.com/browse/CNV-53448
```release-note
None
```
=> tests: Improve stability of metric tests

config/manager/manager.template.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/common/labels.go, internal/operands/template-validator/reconcile_test.go, internal/operands/template-validator/resources.go, internal/operands/vm-console-proxy/reconcile.go, internal/operands/vm-console-proxy/reconcile_test.go, tests/scc_annotation_test.go
The annotation pins required SCC.
The OpenShift API dictates that a workload can require an SCC by using the annotation:
https://docs.openshift.com/container-platform/4.17/authentication/managing-security-context-constraints.html#security-context-constraints-requiring_configuring-internal-oauth
`required-scc` prevents different SCCs from being auto-selected by pods. The auto selection can fail in multiple ways: not enough permissions, changes of UID. When combined with pod security admission (on in new clusters in 4.19), this can result in SCCs being selected based on RBAC permissions that violate PSA and results in pods not running.
Fixes: https://issues.redhat.com/browse/CNV-56031
**Special notes for your …
=> feat: Set "openshift.io/required-scc" annotation on deployments

internal/operands/metrics/resources.go, tests/monitoring_test.go
This is a manual cherry-pick of #984
Fixes #
jira-ticket: https://issues.redhat.com/browse/CNV-50785
```release-note
Alert VMStorageClassWarning only for Windows VMs
```
=> [release-v0.18] Alert VMStorageClassWarning only for Windows VMs

api/v1beta1/ssp_types.go, config/crd/bases/ssp.kubevirt.io_ssps.yaml, data/crd/ssp.kubevirt.io_ssps.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, tests/webhook_test.go, vendor/kubevirt.io/ssp-operator/api/v1beta1/ssp_types.go
This allows the OLM to remove the version when updating to the next release v0.22.
Issue: https://issues.redhat.com/browse/CNV-57082
```release-note
Set the API version v1beta1 as not served.
```
=> [release-v0.21] api: set v1beta1 version to not be served

.github/workflows/pull-request.yaml, Dockerfile, api/go.mod, go.mod, validator.Dockerfile
This will allow update of some modules.
Downstream builds already use golang 1.19.
This PR will unblock: https://github.com/kubevirt/ssp-operator/pull/1246
```release-note
None
```
=> [release-v0.16] deps: Update golang version to 1.19

Makefile
=> chore(golangci-lint): Bump golangci-lint 1.64.6

tests/tests_common_test.go
Sometimes, the API server may not be up-to-date and report an object missing. This caused tests to fail, when SSP recreated an object, but API server was still not aware of it.
```release-note
None
```
=> tests: fix race when checking recreated resources

internal/operands/vm-delete-protection/resources.go, tests/vm_delete_protection_test.go
The error message now assists users to understand how to remove the deletion protection. This should improve the user experience.
Fixes # [CNV-57429](https://issues.redhat.com/browse/CNV-57429)
```release-note
VirtualMachine delete protection: Improved error message
```
=> chore(vm-delete-protection): Improve error message

Dockerfile, Makefile, ci-builder/Dockerfile, go.mod, validator.Dockerfile
- Updated golang to version 1.23.6.
- Updated monitoring-linter to version v0.0.8. The previous version without tag stopped working.
```release-note
None
```
=> deps: Update golang and monitoring-linter

internal/controllers/vm_controller.go
`vm_controller` does not show error if PVC or PV do not exist.
This can happen, if the VM is newly created and the PVC and PV were not yet created.
Fixes: https://issues.redhat.com/browse/CNV-35800
Fixes: https://issues.redhat.com/browse/CNV-35801
```release-note
None
```
=> fix: vm_controller: Don't fail if PVC or PV does not exist

tests/tests_suite_test.go
fix: subset of enabled architectures for running e2e tests
This commit adds another variants of arm string to enabled architectures for running e2e tests
Another variant of this PR would be to drop the check completelly
```release-note
fix: subset of enabled architectures for running e2e tests
```
=> fix: subset of enabled architectures for running e2e tests

data/vm-console-proxy-bundle/vm-console-proxy.yaml, internal/operands/vm-console-proxy/defaults.go
Update vm-console-proxy manifests to version `v0.8.1`.
```release-note
Update vm-console-proxy-bundle to v0.8.1
```
=> [release-v0.23] chore: update vm-console-proxy manifests to v0.8.1

data/vm-console-proxy-bundle/vm-console-proxy.yaml, internal/operands/vm-console-proxy/defaults.go
Update vm-console-proxy manifests to version `v0.8.1`.
```release-note
Update vm-console-proxy-bundle to v0.8.1
```
=> [release-v0.22]  chore: update vm-console-proxy manifests to v0.8.1

data/vm-console-proxy-bundle/vm-console-proxy.yaml, internal/operands/vm-console-proxy/defaults.go
Update vm-console-proxy manifests to version `v0.8.1`.
```release-note
Update vm-console-proxy-bundle to v0.8.1
```
=> chore: update vm-console-proxy manifests to v0.8.1

data/vm-console-proxy-bundle/vm-console-proxy.yaml, internal/operands/vm-console-proxy/defaults.go
Update vm-console-proxy manifests to version `v0.6.2`.
```release-note
Update vm-console-proxy-bundle to v0.6.2
```
=> [release-v0.21] chore: update vm-console-proxy manifests to v0.6.2

tests/dataSources_test.go
The default retention policy is `All`, which means that DataSource is not removed when DataImportCron is removed. This caused cluster health check to fail.
```release-note
None
```
=> tests: Set DICT RetentionPolicy to None

tests/dataSources_test.go
Manual cherry-pick of https://github.com/kubevirt/ssp-operator/pull/1240 .
Package `k8s.io/utils/ptr` is not in this version, so I've used a pointer to variable.
The default retention policy is `All`, which means that DataSource is not removed when DataImportCron is removed. This caused cluster health check to fail.
```release-note
None
```
=> [release-v0.18] tests: Set DICT RetentionPolicy to None

tests/tests_common_test.go
The eventually block used global `Gomega` instance, so any failures in `Expect()` failed the whole block, instead of retrying.
Previous PR: https://github.com/kubevirt/ssp-operator/pull/1329
```release-note
None
```
=> tests: fix: Incorrect Eventually block in expectRestoreAfterUpdate()

config/rbac/role.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/operands/data-sources/reconcile.go, internal/operands/metrics/reconcile.go
These objects are created and owned by ssp-operator, so it needs to have permission to delete them.
Otherwise their creation fails with an error like this:
```
servicemonitors.monitoring.coreos.com "prometheus-k8s-rules-cnv" is forbidden: cannot set an ownerRef on a resource you can't delete:
```
```release-note
None
```
=> fix: Add delete permission to PrometheusRules and ServiceMonitors

Dockerfile, ci-builder/Dockerfile, go.mod, validator.Dockerfile
This PR addresses CVE-2025-22871 which bumps the Go version to `1.23.8` according to the [Vulnerability Report](https://pkg.go.dev/vuln/GO-2025-3563)
Fixes CVE-2025-22871
```release-note
None
```
=> Bump Go to 1.23.8

webhooks/convert/convert.go, webhooks/ssp_webhook.go, webhooks/ssp_webhook_test.go
Previous PR did not update webhook code: https://github.com/kubevirt/ssp-operator/pull/1405
```release-note
None
```
=> chore: Update webhook code to use SSP v1beta3

internal/architecture/architecture.go, internal/controllers/setup.go, internal/operands/common-templates/architecture.go, internal/operands/common-templates/architecture_test.go, internal/operands/common-templates/common_templates_suite_test.go, internal/operands/common-templates/constants.go, internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go, internal/operands/data-sources/reconcile.go, internal/operands/data-sources/reconcile_test.go, internal/operands/data-sources/resource.go, internal/template-bundle/bundle.go, internal/template-bundle/bundle_test.go, tests/commonTemplates_test.go, tests/tests_suite_test.go
Added logic to create common templates for multiple architectures.
Implements a part of the SSP work of: https://github.com/kubevirt/enhancements/pull/49
Jira: https://issues.redhat.com/browse/CNV-61575
```release-note
Added logic to create common templates for multiple architectures.
```
=> feat: Add common templates for heterogeneous clusters

Makefile, config/default/kustomization.yaml, config/hco-network-policy/hco_allow_egress_to_api_server.yaml, config/hco-network-policy/k8s_hco-allow-egress-to-dns.yaml, config/hco-network-policy/kustomization.yaml, config/hco-network-policy/ocp_hco-allow-egress-to-dns.yaml, config/manager/manager.template.yaml, config/network-policy/allow_ingress_to_ssp_operator_webhook_and_metrics.yaml, config/network-policy/kustomization.yaml, data/network-policy/allow_ingress_to_ssp_operator_webhook_and_metrics.yaml, hack/csv-generator.go
By adding the hco.kubevirt.io/allow-access-cluster-services label to
SSP's deployment it gains access to the cluster API and DNS. These
network policies are provided by HCO.
Add the --dump-network-policies flag to csv-generator. If set the
csv-generator will dump all additionally network policies required by SSP to
function apart from the ones already provided by adding the
hco.kubevirt.io/allow-access-cluster-services label to SSP's deployment.
Add network policies to kustomize config so they can be tested in
deployments without OLM.
Fixes #
```release-note
NetworkPolicies required by SSP are added
```
=> Add NetworkPolicies required by SSP

tests/webhook_test.go, webhooks/ssp_webhook.go, webhooks/ssp_webhook_test.go
Added architecture validation to webhook.
```release-note
None
```
=> fix: Validate architectures in ".spec.cluster" in webhook

automation/common/versions.sh, internal/architecture/architecture.go, internal/architecture/architecture_test.go, internal/controllers/setup.go, internal/operands/common-templates/constants.go, internal/operands/common-templates/reconcile.go, internal/operands/common-templates/reconcile_test.go, internal/operands/data-sources/constants.go, internal/operands/data-sources/reconcile.go, internal/operands/data-sources/reconcile_test.go, internal/operands/data-sources/resource.go, internal/template-bundle/bundle.go, tests/commonTemplates_test.go, tests/dataSources_test.go, tests/tests_suite_test.go
Added logic for creating `DataSources` and `DataImportCrons` for multiple architectures.
Jira: https://issues.redhat.com/browse/CNV-61574
Jira: https://issues.redhat.com/browse/CNV-61576
This implements part of the VEP: 
https://github.com/kubevirt/enhancements/blob/3f97affd5c9cd591439530f2e5615398c80c3bef/veps/sig-storage/dic-on-heterogeneous-cluster/dic-on-heterogeneous-cluster.md
```release-note
Added support for multi-arch DataSources and DataImportCrons
```
=> feat: Add support for multi-arch DataSources and DataImportCrons

internal/networkpolicies/networkpolicies.go
Using named ports can lead to issues depending on the CNI implemenation in use. Specify the port number for vm-console-proxy's API instead.
Do not add selectors for host networking Pods (e.g. the kubeapi) as this
is very dependent on the CNI in use. E.g. for OVN this doesn't work at
the moment.
Fixes #
```release-note
None
```
=> fix(networkpolicies): Apply multiple fixes to network policies

go.mod, internal/networkpolicies/networkpolicies.go, internal/operands/template-validator/resources.go, internal/template-validator/service/service.go, internal/template-validator/validator/app.go, internal/template-validator/webhooks/hook.go, tests/validator_test.go
Listen on separate ports for metrics and webhooks in template-validator.
This can be useful in the future because it allows to create more specific network policies.
Fixes #
```release-note
Listen on separate ports for metrics and webhooks in template-validator.
```
=> cleanup(template-validator): Listen on separate ports

data/vm-console-proxy-bundle/vm-console-proxy.yaml, internal/operands/vm-console-proxy/defaults.go
Update vm-console-proxy manifests to `v0.9.0`
```release-note
None
```
=> chore: update vm-console-proxy manifests to v0.9.0

automation/common/versions.sh
The CDI version `v1.63.0` was released.
```release-note
None
```
=> ci: Use latest released CDI in CI

automation/common/versions.sh
Sets Kubevirt version to v1.5.x.
Sets CDI version to v1.62.x.
```release-note
None
```
=> [release-v0.23] ci: Set kubevirt and CDI versions to specific minor versions

internal/controllers/vm_controller.go
Removed the "Could not set vm volumes metrics" log since this kind of error is already logged from
the controller-runtime.
Fixes #https://issues.redhat.com/browse/CNV-42458
```release-note
NONE
```
=> Remove the "Could not set vm volumes metrics" log

automation/common/versions.sh
Sets Kubevirt version to `v1.6.x`.
Sets CDI version to `v1.63.x`.
```release-note
None
```
=> [release-v0.24] ci: Set kubevirt and CDI versions to specific minor versions

config/rbac/role.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/operands/template-validator/reconcile.go, internal/operands/template-validator/reconcile_test.go, internal/operands/template-validator/resources.go, tests/validator_test.go
At least one template validator pod should be available. 
This PR adds PodDisruptionBudget object that specifies this.
Fixes: https://issues.redhat.com/browse/CNV-67393
```release-note
Create PodDisruptionBudget for template validator.
```
=> feat: Create PodDisruptionBudget for template validator

config/default/manager_webhook_patch.yaml, config/manager/manager.template.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/operands/metrics/resources.go, internal/operands/template-validator/resources.go
The convention is, that port name should be prefixed with protocol.
https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-requirements-cnf-reqs
The new names are different, because the maximum port name length is 15 characters.
Jira: https://issues.redhat.com/browse/CNV-67392
```release-note
None
```
=> chore: Set port names according to convention

tests/validator_test.go
One time, the tests have failed, because the certificate in template-validator was invalid. I think it was because the validator was loading a new certificate.
This change adds Eventually before the Consistently to allow time for template-validator to stabilize.
```release-note
None
```
=> tests: Improve test stability when deleting a template

config/default/manager_webhook_patch.yaml, config/manager/manager.template.yaml, data/olm-catalog/ssp-operator.clusterserviceversion.yaml, internal/operands/metrics/resources.go, internal/operands/template-validator/resources.go
Manual cherry-pick of: https://github.com/kubevirt/ssp-operator/pull/1514
The convention is, that port name should be prefixed with protocol.
https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-requirements-cnf-reqs
The new names are different, because the maximum port name length is 15 characters.
Jira: https://issues.redhat.com/browse/CNV-67392
```release-note
None
```
=> [release-v0.24] chore: Set port names according to convention

config/manager/manager.template.yaml, internal/operands/template-validator/resources.go, main.go
Added:
- liveliness probe to template validator
- startup probe to ssp operator and template validator
The startup probes are the same as liveliness probes. We don't have specific logic for them.
Jira: https://issues.redhat.com/browse/CNV-67398
```release-note
None
```
=> feat: Add probes to operator and template validator

Makefile, hack/check-commited-changes.sh
`make bundle` now copies manifests to `data` directory. It is called in the GitHub action that checks uncommitted files.
```release-note
None
```
=> ci: Include bundle in check of generated files
